#!/bin/dash

if [ -z "${IPTABLES}" ] ; then
   IPTABLES=/sbin/iptables
fi

NFQUEUE_QUEUE_NUM=$(python -c "from uvm.settings_reader import get_node_settings_item; print get_node_settings_item('untangle-node-idps','nfqueueQueueNum');")

QUEUE_RULE="\
-j NFQUEUE --queue-num $NFQUEUE_QUEUE_NUM --queue-bypass \
-m mark ! --mark 0x1000000/0x1000000 \
-m connbytes --connbytes 0:1000 --connbytes-dir both --connbytes-mode bytes \
-m comment --comment Snort \
"
${IPTABLES} -D FORWARD ${QUEUE_RULE} > /dev/null 2>&1
${IPTABLES} -A FORWARD ${QUEUE_RULE} > /dev/null 2>&1
