#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@MVVM_HOME@/networking/functions
## These are for network configuration settings.
MVVM_NETWORK_PARAMS_FILE=@MVVM_CONF@/networking.sh

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

if [ -f ${MVVM_NETWORK_PARAMS_FILE} ]; then
    . ${MVVM_NETWORK_PARAMS_FILE}
else
    echo "File ${MVVM_NETWORK_PARAMS_FILE} not found."
    exit 0
fi

## If necessary Run the post configuration script
if [ -n "${MVVM_POST_CONF}" ]; then 
    ${MVVM_POST_CONF} ; 
else
    ${LOG_DEBUG} "Post configuration script is disabled"
fi

