#! /bin/bash

echo "removing the ipq module"

sudo modprobe -r ip_queue || {
    echo "Unable to remove ipq"
    exit -1
}

echo "unbinding nf_queue"
@PREFIX@/usr/bin/nfutil unbind || {
    echo "Unable to unbind nfqueue"
    exit -1
}

true


