#!/bin/sh

echo "removing the ipq module"

sudo modprobe -r ip_queue || {
    echo "Unable to remove ipq"
    exit -1
}

echo "unbinding nf_queue"
@UVM_HOME@/networking/nfutil unbind || {
    echo "Unable to unbind nfqueue"
    exit -1
}

sudo modprobe ip_queue || {
    echo "Unable to reload ip_queue module."
    exit -1
}

true


