#! /bin/bash

exec >> @UVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@UVM_HOME@/networking/functions
## These are for network configuration settings.
UVM_NETWORK_PARAMS_FILE=@UVM_CONF@/networking.sh

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

############################
## Constants
############################

MAIN_RULE_PRIORITY=32766
MAIN_TABLE="main"

DEFAULT_RULE_PRIORITY=32767
DEFAULT_TABLE="default"

UNTANGLE_MAIN_TABLE="${RT_TABLE_NAME_PREFIX}main"
UNTANGLE_MAIN_PRIORITY=${RULE_PRIORITY_BASE}999

## Not using tables until 3.3
TABLE_COUNT=0

############################
## Functions
############################
function flushRoutingRules()
{
    ## Flush all of the custom rules.
    ${IP_CMD} rule show | grep "^${RULE_PRIORITY_BASE}" | \
        sed -e 's|^\([0-9]*\):\(.*\)|ip rule delete \2 priority \1|g' -e 's|from all||g' | \
        sh
    
    ## Fix the rules that should always be in place.
    fixDefaultRules
}

function fixDefaultRules()
{
    ## It is not possible to delete the rule pointing to the local table.
    fixDefaultRule ${MAIN_RULE_PRIORITY} ${MAIN_TABLE}
    fixDefaultRule ${DEFAULT_RULE_PRIORITY} ${DEFAULT_TABLE}

    ## Add in the rule for the untangle table
    # fixDefaultRule ${UNTANGLE_MAIN_PRIORITY} ${UNTANGLE_MAIN_TABLE} 
}

function fixDefaultRule()
{
    local l_priority=$1
    local l_table=$2
    
    local l_test=`${IP_CMD} rule show | grep "^${l_priority}"`

    if [ -z "${l_test}" ]; then
        ${LOG_DEBUG} "Rule for the table ${l_table} does not exist, creating."
        ${IP_CMD} rule add priority ${l_priority} table ${l_table}
    fi
}

function flushRoutingTables()
{
    local t

    ${LOG_DEBUG} "Flushing all of the untangle routing tables"
    ## Function for cleaning up all of the routing tables.
    ## Less than or equal, because the tables start at 1.
    for (( t = 1 ; t <= ${TABLE_COUNT} ; t++ )); do 
        ${IP_CMD} route flush table ${RT_TABLE_NAME_PREFIX}${t}
    done

    ${IP_CMD} route flush table ${UNTANGLE_MAIN_TABLE}

    deleteGateways
}

############################
## Start of script
############################

echo "flushing interfaces" `date`

## Destroy all instances of ppp.
poff -a

## Destroy all of the current bridges
if [ -n "`areBridgesUnconfigured`" ]; then
    deleteAllBridges
else
    echo "Not deleting bridges, bridges already configured."
fi

## Deconfigure all interfaces
deconfigureAllInterfaces

## Clear out all of the interface state.
echo "lo=lo" > /etc/network/ifstate

## Setup the routing rules
flushRoutingRules

## Setup the routing tables
flushRoutingTables

## Guarantee there are no "errors"
true
