#! /bin/bash

exec 2>> @UVM_LOG@/iptables.log

## Print the status of a list of interfaces.  Each interface should be
## given on the command line.

## Return syntax:
## <interface name>: <connected|disconnected|unknown> <10|100|unknown> <full-duplex|half-duplex|unknown>

FLAG_CONNECTED=connected
FLAG_DISCONNECTED=disconnected
FLAG_UNKNOWN=unknown

FLAG_SPEED_100=100
FLAG_SPEED_10=10

FLAG_DUPLEX_FULL=full-duplex
FLAG_DUPLEX_HALF=half-duplex

interfaceList=$*

function getInterfaceStatus()
{
    local t_intf=$1
    local t_isConnected=${FLAG_UNKNOWN}
    local t_speed=${FLAG_UNKNOWN}
    local t_duplex=${FLAG_UNKNOWN}

    local t_status=`mii-tool ${t_intf}`
    if [ -n "${t_status}" ]; then
        if [ "${t_status%link ok}" != "${t_status}" ]; then
            t_isConnected="${FLAG_CONNECTED}"
        else 
            t_isConnected="${FLAG_DISCONNECTED}"
        fi
        
        ## This is kind of unreliable and depends on the order
        if [ "${t_status/100}" != "${t_status}" ]; then
            t_speed="${FLAG_SPEED_100}"
        elif [ "${t_status/10}" != "${t_status}" ]; then
            t_speed="${FLAG_SPEED_10}"
        fi
        
        if [ "${t_status/-FD}" != "${t_status}" ] || [ "${t_status/full duplex}" != "${t_status}" ]; then
            t_duplex="${FLAG_DUPLEX_FULL}"
        elif [ "${t_status/-HD}" != "${t_status}" ] || [ "${t_status/half duplex}" != "${t_status}" ]; then
            t_duplex="${FLAG_DUPLEX_HALF}"
        fi
    else
        ##  Use ethtool instead
        t_status=`ethtool ${t_intf} | grep -v Supported | egrep '(Speed|Duplex|Link detected)' | sed -e '{:start;N;s/\n/ /g;t start}'`
        
        ## Check for link
        if [ "${t_status/Link detected: yes}" != "${t_status}" ]; then
            t_isConnected="${FLAG_CONNECTED}"
        elif [ "${t_status/Link detected: no}" != "${t_status}" ]; then
            t_isConnected="${FLAG_DISCONNECTED}"
        fi
        
        if [ "${t_status/Speed: 100}" != "${t_status}" ]; then
            t_speed="${FLAG_SPEED_100}"
        elif [ "${t_status/Speed: 10}" != "${t_status}" ]; then
            t_speed="${FLAG_SPEED_10}"
        fi
        
        if [ "${t_status/Duplex: Full}" != "${t_status}" ]; then
            t_duplex="${FLAG_DUPLEX_FULL}"
        elif [ "${t_status/Duplex: Half}" != "${t_status}" ]; then
            t_duplex="${FLAG_DUPLEX_HALF}"
        fi
    fi
    
    echo "${t_intf}: ${t_isConnected} ${t_speed} ${t_duplex}"
}

## Iterate through each interface and retrieve the requested information
for t_intf in ${interfaceList} ; do getInterfaceStatus ${t_intf};  done

## ignore any errors
true
