#!/bin/sh

exec >> @UVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@UVM_HOME@/networking/functions
## These are for network configuration settings.
UVM_NETWORK_PARAMS_FILE=@UVM_CONF@/networking.sh

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

if [ -f ${UVM_NETWORK_PARAMS_FILE} ]; then
    . ${UVM_NETWORK_PARAMS_FILE}
else
    echo "File ${UVM_NETWORK_PARAMS_FILE} not found."
    exit 0
fi

## If necessary Run the post configuration script
if [ -n "${UVM_POST_CONF}" ]; then 
    ${UVM_POST_CONF} ; 
else
    ${LOG_DEBUG} "Post configuration script is disabled"
fi

