#!/bin/bash

exec >> @UVM_LOG@/iptables.log 2>&1

t_nonce=`head -n 1 /etc/untangle-net-alpaca/nonce`

ruby <<EOF
require "xmlrpc/client"
 
client = XMLRPC::Client.new( "localhost", "/uvm/api?nonce=${t_nonce}", 3000 )
ok, status = client.call( "generate_rules" )
EOF

exit 0
