#!/bin/dash

rush <<EOF
node_manager = Untangle::RemoteUvmContext.nodeManager
reports_node = node_manager.node("untangle-node-reporting")

if reports_node.nil?
    puts "Reports not installed"
else
    reports_node.flushEvents( )
end
EOF
