Ext.define('Ung.store.Conditions', {
    extend: 'Ext.data.Store',
    storeId: 'conditions',
    fields: ['name', 'displayName', 'type'],
    data: [
        {name:'DST_ADDR', displayName: 'Destination Address'.t(), editorType: 'textfield', vtype:'ipall', visible: true },
        {name:'DST_PORT',displayName: 'Destination Port'.t(), editorType: 'textfield', vtype:'port', visible: true },
        {name:'DST_INTF',displayName: 'Destination Interface'.t(), editorType: 'checkboxgroup', /*values: Util.getInterfaceList(true, false),*/ visible: true},
        {name:'SRC_ADDR',displayName: 'Source Address'.t(), editorType: 'textfield', visible: true, vtype:'ipall'},
        {name:'SRC_PORT',displayName: 'Source Port'.t(), editorType: 'textfield', vtype:'portMatcher', visible: Rpc.directData('rpc.isExpertMode')},
        {name:'SRC_INTF',displayName: 'Source Interface'.t(), editorType: 'checkboxgroup', /*values: Util.getInterfaceList(true, false),*/ visible: true},
        {name:'PROTOCOL',displayName: 'Protocol'.t(), editorType: 'checkboxgroup', values: [['TCP','TCP'],['UDP','UDP'],['any','any']], visible: true},
        {name:'USERNAME',displayName: 'Username'.t(), editorType: 'userselection', /*editor: Ext.create('Ung.UserEditorWindow',{}),*/ visible: true},
        {name:'TAGGED',displayName: 'Tagged'.t(), editorType: 'textfield', visible: true},
        {name:'HOST_HOSTNAME',displayName: 'Host Hostname'.t(), editorType: 'textfield', visible: true},
        {name:'CLIENT_HOSTNAME',displayName: 'Client Hostname'.t(), editorType: 'textfield', visible: false},
        {name:'SERVER_HOSTNAME',displayName: 'Server Hostname'.t(), editorType: 'textfield', visible: false},
        {name:'HOST_MAC', displayName: 'Host MAC Address'.t(), editorType: 'textfield', visible: true },
        {name:'SRC_MAC', displayName: 'Client MAC Address'.t(), editorType: 'textfield', visible: true },
        {name:'DST_MAC', displayName: 'Server MAC Address'.t(), editorType: 'textfield', visible: true },
        {name:'HOST_MAC_VENDOR',displayName: 'Host MAC Vendor'.t(), editorType: 'textfield', visible: true},
        {name:'CLIENT_MAC_VENDOR',displayName: 'Client MAC Vendor'.t(), editorType: 'textfield', visible: false},
        {name:'SERVER_MAC_VENDOR',displayName: 'Server MAC Vendor'.t(), editorType: 'textfield', visible: false},
        {name:'HOST_IN_PENALTY_BOX',displayName: 'Host in Penalty Box'.t(), editorType: 'boolean', visible: false},
        {name:'CLIENT_IN_PENALTY_BOX',displayName: 'Client in Penalty Box'.t(), editorType: 'boolean', visible: false},
        {name:'SERVER_IN_PENALTY_BOX',displayName: 'Server in Penalty Box'.t(), editorType: 'boolean', visible: false},
        {name:'HOST_HAS_NO_QUOTA',displayName: 'Host has no Quota'.t(), editorType: 'boolean', visible: true},
        {name:'USER_HAS_NO_QUOTA',displayName: 'User has no Quota'.t(), editorType: 'boolean', visible: true},
        {name:'CLIENT_HAS_NO_QUOTA',displayName: 'Client has no Quota'.t(), editorType: 'boolean', visible: false},
        {name:'SERVER_HAS_NO_QUOTA',displayName: 'Server has no Quota'.t(), editorType: 'boolean', visible: false},
        {name:'HOST_QUOTA_EXCEEDED',displayName: 'Host has exceeded Quota'.t(), editorType: 'boolean', visible: true},
        {name:'USER_QUOTA_EXCEEDED',displayName: 'User has exceeded Quota'.t(), editorType: 'boolean', visible: true},
        {name:'CLIENT_QUOTA_EXCEEDED',displayName: 'Client has exceeded Quota'.t(), editorType: 'boolean', visible: false},
        {name:'SERVER_QUOTA_EXCEEDED',displayName: 'Server has exceeded Quota'.t(), editorType: 'boolean', visible: false},
        {name:'HOST_QUOTA_ATTAINMENT',displayName: 'Host Quota Attainment'.t(), editorType: 'textfield', visible: true},
        {name:'USER_QUOTA_ATTAINMENT',displayName: 'User Quota Attainment'.t(), editorType: 'textfield', visible: true},
        {name:'CLIENT_QUOTA_ATTAINMENT',displayName: 'Client Quota Attainment'.t(), editorType: 'textfield', visible: false},
        {name:'SERVER_QUOTA_ATTAINMENT',displayName: 'Server Quota Attainment'.t(), editorType: 'textfield', visible: false},
        {name:'HTTP_HOST',displayName: 'HTTP: Hostname'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_REFERER',displayName: 'HTTP: Referrer'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_URI',displayName: 'HTTP: URI'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_URL',displayName: 'HTTP: URL'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_CONTENT_TYPE',displayName: 'HTTP: Content Type'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_CONTENT_LENGTH',displayName: 'HTTP: Content Length'.t(), editorType: 'textfield', visible: true},
        {name:"HTTP_REQUEST_METHOD",displayName: 'HTTP: Request Method'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_REQUEST_METHOD",displayName: 'HTTP: Request Method'.t(), type: 'textfield', visible: false},
        {name:"HTTP_REQUEST_FILE_PATH",displayName: 'HTTP: Request File Path', type: 'textfield', visible: true},
        {name:"WEB_FILTER_REQUEST_FILE_PATH",displayName: 'HTTP: Request File Path'.t(), type: 'textfield', visible: false},
        {name:"HTTP_REQUEST_FILE_NAME",displayName: 'HTTP: Request File Name'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_REQUEST_FILE_NAME",displayName: 'HTTP: Request File Name'.t(), type: 'textfield', visible: false},
        {name:"HTTP_REQUEST_FILE_EXTENSION",displayName: 'HTTP: Request File Extension'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_REQUEST_FILE_EXTENSION",displayName: 'HTTP: Request File Extension'.t(), type: 'textfield', visible: false},
        {name:"HTTP_CONTENT_TYPE",displayName: 'HTTP: Content Type'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_RESPONSE_CONTENT_TYPE",displayName: 'HTTP: Content Type'.t(), type: 'textfield', visible: false},
        {name:"HTTP_RESPONSE_FILE_NAME",displayName: 'HTTP: Response File Name'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_RESPONSE_FILE_NAME",displayName: 'HTTP: Response File Name'.t(), type: 'textfield', visible: false},
        {name:"HTTP_RESPONSE_FILE_EXTENSION",displayName: 'HTTP: Response File Extension'.t(), type: 'textfield', visible: true},
        {name:"WEB_FILTER_RESPONSE_FILE_EXTENSION",displayName: 'HTTP: Response File Extension'.t(), type: 'textfield', visible: false},
        {name:'HTTP_USER_AGENT',displayName: 'HTTP: Client User Agent'.t(), editorType: 'textfield', visible: true},
        {name:'HTTP_USER_AGENT_OS',displayName: 'HTTP: Client User OS'.t(), editorType: 'textfield', visible: false},
        {name:'APPLICATION_CONTROL_APPLICATION',displayName: 'Application Control: Application'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_CATEGORY',displayName: 'Application Control: Application Category'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_PROTOCHAIN',displayName: 'Application Control: Protochain'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_DETAIL',displayName: 'Application Control: Detail'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_CONFIDENCE',displayName: 'Application Control: Confidence'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_PRODUCTIVITY',displayName: 'Application Control: Productivity'.t(), editorType: 'textfield', visible: true},
        {name:'APPLICATION_CONTROL_RISK',displayName: 'Application Control: Risk'.t(), editorType: 'textfield', visible: true},
        {name:'PROTOCOL_CONTROL_SIGNATURE',displayName: 'Application Control Lite: Signature'.t(), editorType: 'textfield', visible: true},
        {name:'PROTOCOL_CONTROL_CATEGORY',displayName: 'Application Control Lite: Category'.t(), editorType: 'textfield', visible: true},
        {name:'PROTOCOL_CONTROL_DESCRIPTION',displayName: 'Application Control Lite: Description'.t(), editorType: 'textfield', visible: true},
        {name:'WEB_FILTER_CATEGORY',displayName: 'Web Filter: Category'.t(), editorType: 'textfield', visible: true},
        {name:'WEB_FILTER_CATEGORY_DESCRIPTION',displayName: 'Web Filter: Category Description'.t(), editorType: 'textfield', visible: true},
        {name:'WEB_FILTER_FLAGGED',displayName: 'Web Filter: Website is Flagged'.t(), editorType: 'boolean', visible: true},
        {name:'DIRECTORY_CONNECTOR_DOMAIN',displayName: 'Directory Connector: User in Domain'.t(), type: 'directorydomainfield', visible: true},
        {name:'DIRECTORY_CONNECTOR_GROUP',displayName: 'Directory Connector: User in Group'.t(), type: 'editor', /*editor: Ext.create('Ung.GroupEditorWindow',{}),*/ visible: true},
        {name:'REMOTE_HOST_COUNTRY',displayName: 'Remote Host Country'.t(), editorType: 'countryselector', /*editor: Ext.create('Ung.CountryEditorWindow',{}),*/ visible: true},
        {name:'CLIENT_COUNTRY',displayName: 'Client Country'.t(), editorType: 'countryselector', /*editor: Ext.create('Ung.CountryEditorWindow',{}),*/ visible: true},
        {name:'SERVER_COUNTRY',displayName: 'Server Country'.t(), editorType: 'countryselector', /*editor: Ext.create('Ung.CountryEditorWindow',{}),*/ visible: true}
    ]


});
