#! /bin/bash

OUTPUT_DIR=output
MD5_FILE=output.md5

e_fileContents=`grep "File contents" ${MD5_FILE} | sed 's/^\([0-9a-f]*\).*$/\1/g'`
e_structure=`grep "Directory structure" ${MD5_FILE} | sed 's/^\([0-9a-f]*\).*$/\1/g'`

a_fileContents=`find ${OUTPUT_DIR} -type f -exec cat \{\} \; | md5sum | sed 's/^\([0-9a-f]*\).*$/\1/g'`
a_structure=`find ${OUTPUT_DIR} | sort | md5sum | sed 's/^\([0-9a-f]*\).*$/\1/g'`

exit_code=0

if [ "${a_fileContents}x" != "${e_fileContents}x" ]; then
    echo "!!!!!!!!!!!!!!!!!!!!!!!"
    echo "  Error, the md5sum for the file contents doesn't match"
    echo "  If there is a required modification in the downloads directory, generate a new md5sum file"
    echo "  with the command 'make md5sum'"
    exit_code=-1
fi
         

if [ "${a_structure}x" != "${e_structure}x" ]; then
    echo "!!!!!!!!!!!!!!!!!!!!!!"
    echo "  Error, the md5sum for the file contents doesn't match"
    echo "  If there is a required modification in the downloads directory, generate a new md5sum file"
    echo "  with the command 'make md5sum'"
    exit_code=-1
fi

exit ${exit_code}