#!/bin/dash

if [ -z "${IPTABLES}" ] ; then
   IPTABLES=/sbin/iptables
fi

# Get the server address for L2TP clients

ADDR="-EMPTY-"
if [ -x /usr/share/untangle/bin/ipsec-l2tp-server-addr ] ; then
   ADDR="`/usr/share/untangle/bin/ipsec-l2tp-server-addr`"
fi

WEBPORT="80"
if [ -x /usr/share/untangle/bin/ipsec-get-http-port ] ; then
    WEBPORT=`/usr/share/untangle/bin/ipsec-get-http-port`
fi

SECPORT="443"
if [ -x /usr/share/untangle/bin/ipsec-get-https-port ] ; then
    SECPORT=`/usr/share/untangle/bin/ipsec-get-https-port`
fi

VPNFLAG="False"
if [ -x /usr/share/untangle/bin/ipsec-get-vpn-flag ] ; then
   VPNFLAG="`/usr/share/untangle/bin/ipsec-get-vpn-flag`"
fi

BYPASSFLAG="True"
if [ -x /usr/share/untangle/bin/ipsec-get-bypass-flag ] ; then
   BYPASSFLAG="`/usr/share/untangle/bin/ipsec-get-bypass-flag`"
fi

# We put the L2TP port forward rules in their own chain that we can flush
# since the server address can be changed by the user meaning there is
# no easy way to find and delete any old rules
${IPTABLES} -t nat -N l2tp-forward-rules >/dev/null 2>&1
${IPTABLES} -t nat -F l2tp-forward-rules >/dev/null 2>&1

#
# Allow IPsec traffic through the NAT reverse filter
#
${IPTABLES} -t filter -D nat-reverse-filter -m policy --pol ipsec --dir in  -j RETURN -m comment --comment "allow IPsec traffic" >/dev/null 2>&1
${IPTABLES} -t filter -D nat-reverse-filter -m policy --pol ipsec --dir out -j RETURN -m comment --comment "allow IPsec traffic" >/dev/null 2>&1

${IPTABLES} -t filter -I nat-reverse-filter -m policy --pol ipsec --dir in  -j RETURN -m comment --comment "allow IPsec traffic"
${IPTABLES} -t filter -I nat-reverse-filter -m policy --pol ipsec --dir out -j RETURN -m comment --comment "allow IPsec traffic"

#
# Do not NAT ipsec traffic even if its leaving a WAN
#
${IPTABLES} -t nat -D nat-rules -m policy --pol ipsec --dir out -j RETURN -m comment --comment "dont NAT IPsec traffic" >/dev/null 2>&1
${IPTABLES} -t nat -I nat-rules -m policy --pol ipsec --dir out -j RETURN -m comment --comment "dont NAT IPsec traffic"

#
# Bypass all IPsec traffic if the bypass flag is set
#
${IPTABLES} -t filter -D bypass-rules -m policy --pol ipsec --dir out --goto set-bypass-mark >/dev/null 2>&1
${IPTABLES} -t filter -D bypass-rules -m policy --pol ipsec --dir in  --goto set-bypass-mark >/dev/null 2>&1

if [ $BYPASSFLAG = "True" ]
then
    ${IPTABLES} -t filter -I bypass-rules -m policy --pol ipsec --dir out --goto set-bypass-mark
    ${IPTABLES} -t filter -I bypass-rules -m policy --pol ipsec --dir in  --goto set-bypass-mark
fi

#
# NAT traffic from L2TP interfaces
#
${IPTABLES} -t nat -D nat-rules -m connmark --mark 0xfb/0xff -j MASQUERADE -m comment --comment "NAT l2tp traffic" >/dev/null 2>&1
${IPTABLES} -t nat -I nat-rules -m connmark --mark 0xfb/0xff -j MASQUERADE -m comment --comment "NAT l2tp traffic"

#
# Allow L2TP traffic to penetrate NATd networks
#
${IPTABLES} -t filter -D nat-reverse-filter -m mark --mark 0xfb/0xff -j RETURN -m comment --comment "Allow L2TP" >/dev/null 2>&1
${IPTABLES} -t filter -I nat-reverse-filter -m mark --mark 0xfb/0xff -j RETURN -m comment --comment "Allow L2TP"

# Add the jump rule for the L2TP port forwards
${IPTABLES} -t nat -D port-forward-rules -j l2tp-forward-rules -m comment --comment "Port forward jump for L2TP" >/dev/null 2>&1
${IPTABLES} -t nat -I port-forward-rules -j l2tp-forward-rules -m comment --comment "Port forward jump for L2TP"

# if we don't have a valid L2TP server address then IPsec is likely not installed or configured
if [ $ADDR = "-EMPTY-" ]
then
    return
fi

# we also don't want to add these rules if the VPN stuff is disabled
if [ $VPNFLAG = "False" ]
then
    return
fi

#
# Add port forward rules for L2TP and Xauth clients.  We need the port 53 rules
# for Xauth clients since the server side of the L2TP interface will not exist
# if no L2TP clients are connected.  Using the L2TP server side addresses for
# Xauth clients ended up being cleaner than trying to use the WAN interface.
# We also don't need to do delete cleanup here since we're using dedicated
# chains that were flushed above.
#
${IPTABLES} -t nat -I l2tp-forward-rules -p tcp -d $ADDR --destination-port $SECPORT -j REDIRECT --to-ports 443 -m comment --comment "Send L2TP to apache"
${IPTABLES} -t nat -I l2tp-forward-rules -p tcp -d $ADDR --destination-port $WEBPORT -j REDIRECT --to-ports 80 -m comment --comment "Send L2TP to apache"
${IPTABLES} -t nat -I l2tp-forward-rules -p tcp -d $ADDR --destination-port 53 -j REDIRECT --to-ports 53 -m comment --comment "Send L2TP tcp to dnsmasq"
${IPTABLES} -t nat -I l2tp-forward-rules -p udp -d $ADDR --destination-port 53 -j REDIRECT --to-ports 53 -m comment --comment "Send L2TP udp to dnsmasq"

# This special rule blocks L2TP udp traffic on 1701 without IPsec
${IPTABLES} -t filter -D filter-rules-input -p udp --dport 1701 -m policy --dir in --pol none -j DROP -m comment --comment "drop L2TP without IPsec" >/dev/null 2>&1
${IPTABLES} -t filter -I filter-rules-input -p udp --dport 1701 -m policy --dir in --pol none -j DROP -m comment --comment "drop L2TP without IPsec"

