#!/bin/dash

if [ -z "$IPTABLES" ] ; then IPTABLES=iptables ; fi

POOL="-EMPTY-"
if [ -x /usr/share/untangle/bin/ipsec-xauth-cidr-block ] ; then
   POOL="`/usr/share/untangle/bin/ipsec-xauth-cidr-block`"
fi

VPNFLAG="False"
if [ -x /usr/share/untangle/bin/ipsec-get-vpn-flag ] ; then
   VPNFLAG="`/usr/share/untangle/bin/ipsec-get-vpn-flag`"
fi

# we put the rules to mark the ipsec xauth interface in their own chains since
# the cidr pool is used to identify the traffic and that could be changed
# by the user so we start by creating and flushing the chains
${IPTABLES} -t mangle -N ipsec-xauth-src >/dev/null 2>&1
${IPTABLES} -t mangle -N ipsec-xauth-dst >/dev/null 2>&1
${IPTABLES} -t mangle -F ipsec-xauth-src >/dev/null 2>&1
${IPTABLES} -t mangle -F ipsec-xauth-dst >/dev/null 2>&1

# delete old jump rules (if they exist)
${IPTABLES} -t mangle -D mark-src-intf -j ipsec-xauth-src -m comment --comment "src interface jump for Xauth" >/dev/null 2>&1
${IPTABLES} -t mangle -D mark-dst-intf -j ipsec-xauth-dst -m comment --comment "dst interface jump for Xauth" >/dev/null 2>&1

# delete old nat-rules rule
${IPTABLES} -t nat -D nat-rules -m mark --mark 0xfc/0xff -j MASQUERADE -m comment --comment "NAT Xauth traffic" >/dev/null 2>&1

# delete old nat-reverse-filter rule
${IPTABLES} -t filter -D nat-reverse-filter -m mark --mark 0xfc/0xff -j RETURN -m comment --comment "Allow Xauth" >/dev/null 2>&1 

# if we don't have a valid Xauth pool then IPsec is likely not installed or configured
if [ $POOL = "-EMPTY-" ]
then
    return
fi

# we also don't want to add these rules if the VPN stuff is disabled
if [ $VPNFLAG = "False" ]
then
    return
fi

# first we add rules to the Xauth mark chains we prepared above
${IPTABLES} -t mangle -I ipsec-xauth-src -s $POOL -j MARK --set-mark 0xfc/0xff -m comment --comment "Set src interface mark for Xauth"
${IPTABLES} -t mangle -A ipsec-xauth-src -s $POOL -j CONNMARK --save-mark --mask 0xFFFF -m comment --comment "Copy mark to connmark for Xauth"
${IPTABLES} -t mangle -I ipsec-xauth-dst -d $POOL -j MARK --set-mark 0xfc00/0xff00 -m comment --comment "Set dst interface mark for Xauth"
${IPTABLES} -t mangle -A ipsec-xauth-dst -d $POOL -j CONNMARK --save-mark --mask 0xFFFF -m comment --comment "Copy mark to connmark for Xauth"

# Add jump rules for xauth traffic.  These must be inserted ABOVE the line that
# returns if the marks are already set, otherwise the mark for the physical
# interface where the Xauth/IPsec traffic arrived will overwrite the special
# mark we using for our pseudo/virtual interface for Xauth traffic.
${IPTABLES} -t mangle -I mark-src-intf -j ipsec-xauth-src -m comment --comment "src interface jump for Xauth"
${IPTABLES} -t mangle -I mark-dst-intf -j ipsec-xauth-dst -m comment --comment "dst interface jump for Xauth"

# insert nat-reverse-filter rule to allow Xauth to penetrate NATd networks 
${IPTABLES} -t filter -I nat-reverse-filter -m mark --mark 0xfc/0xff -j RETURN -m comment --comment "Allow Xauth" 

# insert nat-rules rule for traffic from xauth network
${IPTABLES} -t nat -I nat-rules -m mark --mark 0xfc/0xff -j MASQUERADE -m comment --comment "NAT Xauth traffic"

