#!/usr/bin/python

import urlparse
import requests
import json
import sys
import os

#------------------------------------------------------------------------------

def handle_google(logfile,authcode,cid,secret):
	authdata = {}
	authdata['code'] = authcode
	authdata['client_id'] = cid
	authdata['client_secret'] = secret
	authdata['redirect_uri'] = 'https://auth-relay.untangle.com/callback.php'
	authdata['grant_type'] = 'authorization_code'
	authresp = requests.post("https://www.googleapis.com/oauth2/v4/token", data=authdata)
	authtext = authresp.text;

	logfile.write("AUTH: %s\n" % (authtext));
	authjson = json.loads(authtext)

	if (not "access_token" in authjson):
		return("ERROR: missing access")

	userdata = {}
	userdata['access_token'] = authjson['access_token']
	userresp = requests.get("https://www.googleapis.com/plus/v1/people/me", params=userdata)
	usertext = userresp.text

	logfile.write("USER: %s\n" % (usertext));
	userjson = json.loads(usertext)

	if ("emails" in userjson):
		for item in userjson['emails']:
			if (item['type'].upper() == 'ACCOUNT'):
				return(item['value'])

	if ("displayName" in userjson):
		return(userjson['displayName'])

	return("ERROR: missing identity")

#------------------------------------------------------------------------------

def handle_facebook(logfile,authcode,cid,secret):
	authdata = {}
	authdata['code'] = authcode
	authdata['client_id'] = cid
	authdata['client_secret'] = secret
	authdata['redirect_uri'] = 'https://auth-relay.untangle.com/callback.php'
	authdata['grant_type'] = 'authorization_code'
	authresp = requests.get("https://graph.facebook.com/v2.9/oauth/access_token", params=authdata)
	authtext = authresp.text;

	logfile.write("AUTH: %s\n" % (authtext));
	authjson = json.loads(authtext)

	if (not "access_token" in authjson):
		return("ERROR: missing access")

	userdata = {}
	userdata['access_token'] = authjson['access_token']
	userdata['fields'] = 'id,name,email'
	userresp = requests.get("https://graph.facebook.com/me", params=userdata)
	usertext = userresp.text

	logfile.write("USER: %s\n" % (usertext));
	userjson = json.loads(usertext)

	if ("email" in userjson):
		return(userjson['email'])

	if ("name" in userjson):
		return(userjson['name'])

	return("ERROR: missing identity")

#------------------------------------------------------------------------------

def handle_microsoft(logfile,authcode,cid,secret):
	authdata = {}
	authdata['code'] = authcode
	authdata['client_id'] = cid
	authdata['client_secret'] = secret
	authdata['redirect_uri'] = 'https://auth-relay.untangle.com/callback.php'
	authdata['grant_type'] = 'authorization_code'
	authresp = requests.post("https://login.microsoftonline.com/common/oauth2/v2.0/token", data=authdata)
	authtext = authresp.text;

	logfile.write("AUTH: %s\n" % (authtext));
	authjson = json.loads(authtext)

	if (not "access_token" in authjson):
		return("ERROR: missing access")

	userhead = {}
	userhead['Authorization'] = ('Bearer ' + authjson['access_token'])
	userresp = requests.get("https://graph.microsoft.com/v1.0/me", headers=userhead)
	usertext = userresp.text

	logfile.write("USER: %s\n" % (usertext));
	userjson = json.loads(usertext)

	if ("userPrincipalName" in userjson):
		return(userjson['userPrincipalName'])

	if ("displayName" in userjson):
		return(userjson['displayName'])

	return("ERROR: missing identity")

#------------------------------------------------------------------------------

# The list of applications and corresponding secrets for each platform
platform_data = [
	{ "vendor": "GOOGLE", "cid": "365238258169-6k7k0ett96gv2c8392b9e1gd602i88sr.apps.googleusercontent.com", "secret": "76RDgNAPNwZ6-frswmLPDaRJ" },
	{ "vendor": "MICROSOFT", "cid": "f8285e96-b240-4036-8ea5-f37cf6b981bb", "secret": "7lA3P6.aO3Y2.-w2B6v33i1P.cP1DSpCCT" },
	{ "vendor": "FACEBOOK", "cid": "1840471182948119", "secret": "0f93a8ce9631adf41115447354432bb8" }
]

qstring = None

sys.stdout.write("Content-type: text\n\n")

if ("QUERY_STRING" in os.environ):
	qstring = os.environ['QUERY_STRING']

if (qstring == None):
	sys.stdout.write("ERROR: missing query string in getClientToken script")
	sys.exit()

qparams = urlparse.parse_qs(qstring)

if ('authPlatform' in qparams):
	auth_platform = qparams['authPlatform'][0]
else:
	sys.stdout.write("ERROR: missing authPlatform in getClientToken script")
	sys.exit()

if ('authCode' in qparams):
	auth_code = qparams['authCode'][0]
else:
	sys.stdout.write("ERROR: missing authCode in getClientToken script")
	sys.exit()

logfile = open("/tmp/getClientToken.log","a")
logfile.write("%s\n" % ("--------------------"));
logfile.write("QUERY: %s\n" % (qstring));
logfile.write("PLATFORM: %s\n" % (auth_platform));
logfile.write("AUTHCODE: %s\n" % (auth_code));

# start with an error that will get replaced if we find valid data
result = "ERROR: Unknown authPlatform in getClientToken script"

for entry in platform_data:
	if entry['cid'] != auth_platform:
		continue
	if entry['vendor'] == "GOOGLE":
		result = handle_google(logfile,auth_code,entry['cid'],entry['secret'])
	if entry['vendor'] == "FACEBOOK":
		result = handle_facebook(logfile,auth_code,entry['cid'],entry['secret'])
	if entry['vendor'] == "MICROSOFT":
		result = handle_microsoft(logfile,auth_code,entry['cid'],entry['secret'])
	break

logfile.write("XMIT: %s\n" % (result));
logfile.close()

sys.stdout.write(result)
sys.exit()
