#!/bin/dash

mkdir -p @PREFIX@/var/log/shield
exec >> @PREFIX@/var/log/shield/monitor.log 2>&1

SHIELD_BIND_PORT=3001

/etc/init.d/untangle-shield start

echo "[`date`] Started the shield."

is_running()
{
    curl -sf -F 'json_request=@-' -m 2 "http://localhost:${SHIELD_BIND_PORT}"  > /dev/null 2>&1 <<EOF
{ "function" : "hello_world" }
EOF
}

for t in `seq 1 10`; do
    sleep 1

    is_running && break
done

echo "[`date`] Waited ${t} seconds for the shield to start."
