{
    "settingsVersion":5,
    "configured":true,
    "javaClass":"com.untangle.node.bandwidth_control.BandwidthControlSettings",
    "rules":{
        "javaClass":"java.util.LinkedList",
        "list":[]
    }
}