#! /bin/sh

FILE=/etc/default/untangle-hw

echo "  Customizing HW-related settings for untangle-vm"

ARCH=`uname -m`
MEM=$(awk '/MemTotal/ { print $2 }' < /proc/meminfo)
if [ $MEM -gt 3900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=1200m
        MAX_BERKDB_MEG=150
    else
        MAX_HEAP_SIZE=960m
        MAX_BERKDB_MEG=120
    fi
elif [ $MEM -gt 1900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=800m
        MAX_BERKDB_MEG=100
    else
        MAX_HEAP_SIZE=640m
        MAX_BERKDB_MEG=80
    fi
elif [ $MEM -gt 900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=380m
        MAX_BERKDB_MEG=48
    else
        MAX_HEAP_SIZE=320m
        MAX_BERKDB_MEG=32
    fi
else
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=260m
        MAX_BERKDB_MEG=24
    else
        MAX_HEAP_SIZE=220m
        MAX_BERKDB_MEG=20
    fi
fi

echo "    Maximum heap size -> $MAX_HEAP_SIZE"
echo "    Maximum BDB size -> ${MAX_BERKDB_MEG}M"

cat >| $FILE <<EOF
MAX_HEAP_SIZE=$MAX_HEAP_SIZE
MAX_BERKDB_MEG=$MAX_BERKDB_MEG
EOF
