#! /bin/bash

#
# The script sets a plethora of untangle-vm parameters based on hardware
# such as 32bit vs 64bit, memory size, etc.
#
# IMPORTANT:
# It is not recommended to give over 50% of the memory to the java heap
# This has shown to lead to load spikes and instability on the system.
#

FILE=/usr/share/untangle/conf/untangle-hw.conf

echo "  Customizing HW-related settings for untangle-vm"

ARCH=`uname -m`
MEM=$(awk '/MemTotal/ { print $2 }' < /proc/meminfo)
if [ $MEM -gt 4900000 ] ; then
    if [ $ARCH = 'i686' ]; then
        # if 32-bit, still only use 2/6gig because otherwise java errors out
        MAX_HEAP_SIZE=2000m
    else
        MAX_HEAP_SIZE=`echo $MEM | awk '{printf int($1 * .5 / 1000) "m"}'`
    fi
    GC_SAFETY_FACTOR=10
    GC_MIN_CYCLE=1
    REPORTS_MAX_QUEUE_LEN=1000000
elif [ $MEM -gt 3900000 ] ; then
    MAX_HEAP_SIZE=2000m
    GC_SAFETY_FACTOR=10
    GC_MIN_CYCLE=2
    REPORTS_MAX_QUEUE_LEN=1000000
elif [ $MEM -gt 2900000 ] ; then
    MAX_HEAP_SIZE=1500m
    GC_SAFETY_FACTOR=20
    GC_MIN_CYCLE=5
    REPORTS_MAX_QUEUE_LEN=1000000
elif [ $MEM -gt 1900000 ] ; then
    MAX_HEAP_SIZE=820m
    GC_SAFETY_FACTOR=50
    GC_MIN_CYCLE=10
    REPORTS_MAX_QUEUE_LEN=750000
elif [ $MEM -gt 900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=420m
    else
        MAX_HEAP_SIZE=420m
    fi
    GC_SAFETY_FACTOR=90
    GC_MIN_CYCLE=10
    REPORTS_MAX_QUEUE_LEN=500000
elif [ $MEM -gt 600000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=320m
    else
        MAX_HEAP_SIZE=320m
    fi
    GC_SAFETY_FACTOR=90
    GC_MIN_CYCLE=10
    REPORTS_MAX_QUEUE_LEN=100000
else
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=256m
    else
        MAX_HEAP_SIZE=100m
    fi
    GC_SAFETY_FACTOR=90
    GC_MIN_CYCLE=10
    REPORTS_MAX_QUEUE_LEN=50000
fi

if [ $ARCH = 'x86_64' ]; then
    SESSION_LIMIT=0
else
    SESSION_LIMIT=10000
fi

echo "    Maximum heap size        -> ${MAX_HEAP_SIZE}"
echo "    GC safety factor         -> ${GC_SAFETY_FACTOR}"
echo "    GC minimum cycle         -> ${GC_MIN_CYCLE}"
echo "    Session limit            -> ${SESSION_LIMIT}"
echo "    Reports queue limit      -> ${REPORTS_MAX_QUEUE_LEN}"

#
# Apply the settings
#

mkdir -p `dirname $FILE`
cat >| $FILE <<EOF
max_heap_size="$MAX_HEAP_SIZE"
gc_safety_factor="$GC_SAFETY_FACTOR"
gc_min_cycle="$GC_MIN_CYCLE"
session_limit="$SESSION_LIMIT"
reports_max_queue_len="$REPORTS_MAX_QUEUE_LEN"
EOF

