Ext.define('Ung.util.Map', {
    singleton: true,
    alternateClassName: 'Map',

    init: function () {
        this.buildInterfacesMap();
    },

    buildInterfacesMap: function () {
        var interfaces = [], map = {};
        try {
            interfaces = Rpc.directData('rpc.reportsManager.getInterfacesInfo').list;
        } catch (ex) {
            console.log(ex);
        }
        Ext.Array.each(interfaces, function (intf) {
            map[intf.interfaceId] = intf.name;
        });
        this.interfaces = map;
    },

    columns: {
        'request_id': { text: 'Request Id'.t(), colWidth: 100 },
        'time_stamp': { text: 'Timestamp'.t(), colWidth: 180 },
        'session_id': { text: 'Session Id'.t(), colWidth: 120 },
        'client_intf': { text: 'Client Interface'.t(), colWidth: 120 },
        'server_intf': { text: 'Server Interface'.t(), colWidth: 120 },
        'c_client_addr': { text: 'Client'.t(), colWidth: 120 },
        's_client_addr': { text: 'New Client'.t(), colWidth: 120 },
        'c_server_addr': { text: 'Original Server'.t(), colWidth: 120 },
        's_server_addr': { text: 'Server'.t(), colWidth: 120 },
        'c_client_port': { text: 'Client Port'.t(), colWidth: 120 },
        's_client_port': { text: 'New Client Port'.t(), colWidth: 120 },
        'c_server_port': { text: 'Original Server Port'.t(), colWidth: 120 },
        's_server_port': { text: 'Server Port'.t(), colWidth: 120 },
        'client_country': { text: 'Client Country'.t(), colWidth: 120 },
        'client_latitude': { text: 'Client Latitude'.t(), colWidth: 120 },
        'client_longitude': { text: 'Client Longitude'.t(), colWidth: 120 },
        'server_country': { text: 'Server Country'.t(), colWidth: 120 },
        'server_latitude': { text: 'Server Latitude'.t(), colWidth: 120 },
        'server_longitude': { text: 'Server Longitude'.t(), colWidth: 120 },
        'policy_id': { text: 'Policy Id'.t(), colWidth: 120 },
        'username': { text: 'Username'.t(), colWidth: 120 },
        'hostname': { text: 'Hostname'.t(), colWidth: 120 },
        'method': { text: 'Method'.t(), colWidth: 120 },
        'uri': { text: 'URI'.t(), colWidth: 120 },
        'host': { text: 'Host'.t(), colWidth: 250 },
        'domain': { text: 'Domain'.t(), colWidth: 120 },
        'referer': { text: 'Referer'.t(), colWidth: 120 },
        'c2s_content_length': { text: 'Upload Content Length'.t(), colWidth: 120 },
        's2c_content_length': { text: 'Download Content Length'.t(), colWidth: 120 },
        's2c_content_type': { text: 'Content Type'.t(), colWidth: 120 },
        's2c_content_filename': { text: 'Content Filename'.t(), colWidth: 120 },
        'ad_blocker_cookie_ident': { text: 'Blocked Cookie'.t() + ' (Ad Blocker)', colWidth: 120 },
        'ad_blocker_action': { text: 'Action'.t() + ' (Ad Blocker)', colWidth: 120 },
        'web_filter_reason': { text: 'Reason For Action'.t() + ' (Web Filter)', colWidth: 120 },
        'web_filter_category_id': { text: 'Web Category'.t() + ' (Web Filter)', colWidth: 250 },
        'web_filter_rule_id': { text: 'Web Rule'.t() + ' (Web Filter)', colWidth: 120 },
        'web_filter_blocked': { text: 'Blocked'.t() + ' (Web Filter)', colWidth: 120 },
        'web_filter_flagged': { text: 'Flagged'.t() + ' (Web Filter)', colWidth: 120 },
        'virus_blocker_lite_clean': { text: 'Clean'.t() + ' (Virus Blocker Lite)', colWidth: 120 },
        'virus_blocker_lite_name': { text: 'Virus Name'.t() + ' (Virus Blocker Lite)', colWidth: 120 },
        'virus_blocker_clean': { text: 'Clean'.t() + ' (Virus Blocker)', colWidth: 120 },
        'virus_blocker_name': { text: 'Virus Name'.t() + ' (Virus Blocker)', colWidth: 120 },
        'threat_prevention_blocked': { text: 'Blocked'.t() + ' (Threat Prevention)', colWidth: 120 },
        'threat_prevention_flagged': { text: 'Flagged'.t() + ' (Threat Prevention)', colWidth: 120 },
        'threat_prevention_rule_id': { text: 'Rule'.t() + ' (Threat Prevention)', colWidth: 120 },
        'threat_prevention_reputation': { text: 'Reputation'.t() + ' (Threat Prevention)', colWidth: 120 },
        'threat_prevention_categories': { text: 'Categories'.t() + ' (Threat Prevention)', colWidth: 120 }
    },

    httpReason: {
        D: 'in Categories Block list'.t(),
        U: 'in Site Block list'.t(),
        T: 'in Search Term list'.t(),
        E: 'in File Block list'.t(),
        M: 'in MIME Types Block list'.t(),
        H: 'hostname is an IP address'.t(),
        I: 'in Site Pass list'.t(),
        R: 'referer in Site Pass list'.t(),
        C: 'in Clients Pass list'.t(),
        B: 'in Temporary Unblocked list'.t(),
        F: 'in Rules list'.t(),
        K: 'Kid-friendly redirect'.t(),
        default: 'no rule applied'.t()
    },

    webCategory: {
        0: 'Uncategorized',
        1: 'Real Estate',
        2: 'Computer and Internet Security',
        3: 'Financial Services',
        4: 'Business and Economy',
        5: 'Computer and Internet Info',
        6: 'Auctions',
        7: 'Shopping',
        8: 'Cult and Occult',
        9: 'Travel',
        10: 'Abused Drugs',
        11: 'Adult and Pornography',
        12: 'Home and Garden',
        13: 'Military',
        14: 'Social Networking',
        15: 'Dead Sites',
        16: 'Individual Stock Advice and Tools',
        17: 'Training and Tools',
        18: 'Dating',
        19: 'Sex Education',
        20: 'Religion',
        21: 'Entertainment and Arts',
        22: 'Personal sites and Blogs',
        23: 'Legal',
        24: 'Local Information',
        25: 'Streaming Media',
        26: 'Job Search',
        27: 'Gambling',
        28: 'Translation',
        29: 'Reference and Research',
        30: 'Shareware and Freeware',
        31: 'Peer to Peer',
        32: 'Marijuana',
        33: 'Hacking',
        34: 'Games',
        35: 'Philosophy and Political Advocacy',
        36: 'Weapons',
        37: 'Pay to Surf',
        38: 'Hunting and Fishing',
        39: 'Society',
        40: 'Educational Institutions',
        41: 'Online Greeting Cards',
        42: 'Sports',
        43: 'Swimsuits and Intimate Apparel',
        44: 'Questionable',
        45: 'Kids',
        46: 'Hate and Racism',
        47: 'Personal Storage',
        48: 'Violence',
        49: 'Keyloggers and Monitoring',
        50: 'Search Engines',
        51: 'Internet Portals',
        52: 'Web Advertisements',
        53: 'Cheating',
        54: 'Gross',
        55: 'Web-based Email',
        56: 'Malware Sites',
        57: 'Phishing and Other Frauds',
        58: 'Proxy Avoidance and Anonymizers',
        59: 'Spyware and Adware',
        60: 'Music',
        61: 'Government',
        62: 'Nudity',
        63: 'News and Media',
        64: 'Illegal',
        65: 'Content Delivery Networks',
        66: 'Internet Communications',
        67: 'Bot Nets',
        68: 'Abortion',
        69: 'Health and Medicine',
        71: 'SPAM URLs',
        74: 'Dynamically Generated Content',
        75: 'Parked Domains',
        76: 'Alcohol and Tobacco',
        78: 'Image and Video Search',
        79: 'Fashion and Beauty',
        80: 'Recreation and Hobbies',
        81: 'Motor Vehicles',
        82: 'Web Hosting'
    }
});
