FROM docker.untangle.int/ngfw:base
MAINTAINER Sebastien Delafond <sdelafond@gmail.com>

RUN apt-get install --yes untangle-development-build

ENV SRC=/opt/untangle/ngfw_src
RUN mkdir -p ${SRC}
VOLUME ${SRC}

WORKDIR ${SRC}

ENTRYPOINT rake
