FROM untangleinc/ngfw:buster-base
LABEL maintainer="Sebastien Delafond <sdelafond@gmail.com>"

# do not use official Debian mirrors
RUN rm /etc/apt/sources.list

RUN echo "deb http://package-server.untangle.int/public/buster current main non-free" > /etc/apt/sources.list.d/current.list
