/*
 * Copyright (c) 2003-2007 Untangle, Inc.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Untangle, Inc. ("Confidential Information"). You shall
 * not disclose such Confidential Information.
 *
 * $Id$
 */


package com.untangle.tran.test.gui;

import com.untangle.mvvm.tran.TransformContext;
import com.untangle.tran.test.TestSettings;
import com.untangle.tran.test.TestTransform;
import com.untangle.gui.util.Util;

public class AdvancedControlsJPanel extends javax.swing.JPanel {
    
    private TransformContext transformContext;
    private TestSettings transformSettings;
    
    
    public AdvancedControlsJPanel(TransformContext transformContext) {
        this.transformContext = transformContext;
        
        initComponents();
        
        
        if(transformContext != null){
            transformSettings =  ((TestTransform)transformContext.transform()).getTestSettings();
            // FIXME: DEPRECATED
            // doubleEndpointJCheckBox.setSelected(transformSettings.modeDEM());
            bufferedJCheckBox.setSelected(transformSettings.isBuffered());
            normalJCheckBox.setSelected(transformSettings.isNormal());
            releaseJCheckBox.setSelected(transformSettings.getRelease());
            quietJCheckBox.setSelected(transformSettings.isQuiet());
            randomBufferSizeJCheckBox.setSelected(transformSettings.getRandomBufferSizes());
            minJSpinner.setValue( new Integer(transformSettings.getMinRandomBufferSize()) );
            maxJSpinner.setValue( new Integer(transformSettings.getMaxRandomBufferSize()) );
        }
         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        doubleEndpointJCheckBox = new javax.swing.JCheckBox();
        bufferedJCheckBox = new javax.swing.JCheckBox();
        normalJCheckBox = new javax.swing.JCheckBox();
        releaseJCheckBox = new javax.swing.JCheckBox();
        quietJCheckBox = new javax.swing.JCheckBox();
        randomBufferSizeJCheckBox = new javax.swing.JCheckBox();
        minJSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maxJSpinner = new javax.swing.JSpinner();
        commitJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doubleEndpointJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        doubleEndpointJCheckBox.setText("Double Endpoint");
        add(doubleEndpointJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        bufferedJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        bufferedJCheckBox.setText("Buffered");
        add(bufferedJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        normalJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        normalJCheckBox.setText("Normal");
        add(normalJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        releaseJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        releaseJCheckBox.setText("Release");
        add(releaseJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        quietJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        quietJCheckBox.setText("Quiet (read only)");
        add(quietJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        randomBufferSizeJCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        randomBufferSizeJCheckBox.setText("Use Random Buffer Size");
        add(randomBufferSizeJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        minJSpinner.setFont(new java.awt.Font("Dialog", 0, 12));
        add(minJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel1.setText("min:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("max:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, -1, -1));

        maxJSpinner.setFont(new java.awt.Font("Dialog", 0, 12));
        add(maxJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, -1));

        commitJButton.setFont(new java.awt.Font("Dialog", 0, 12));
        commitJButton.setText("Commit");
        commitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitJButtonActionPerformed(evt);
            }
        });

        add(commitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

    }//GEN-END:initComponents

    private void commitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitJButtonActionPerformed
        if( transformContext == null)
            return;
        
        // FIXME
        // transformSettings.modeDEM(doubleEndpointJCheckBox.isSelected());
        transformSettings.setBuffered(bufferedJCheckBox.isSelected());
        transformSettings.setNormal(normalJCheckBox.isSelected());
        transformSettings.setRelease(releaseJCheckBox.isSelected());
        transformSettings.setQuiet(quietJCheckBox.isSelected());
        transformSettings.setRandomBufferSizes(randomBufferSizeJCheckBox.isSelected());
        transformSettings.setMinRandomBufferSize( ((Integer)minJSpinner.getValue()).intValue() );
        transformSettings.setMaxRandomBufferSize( ((Integer)maxJSpinner.getValue()).intValue() );
        try { 
            ((TestTransform)transformContext.transform()).setTestSettings(transformSettings); 
        } catch (Exception e) {
            Util.handleExceptionNoRestart("Error comitting", e); 
        }
        
    }//GEN-LAST:event_commitJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bufferedJCheckBox;
    private javax.swing.JButton commitJButton;
    private javax.swing.JCheckBox doubleEndpointJCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner maxJSpinner;
    private javax.swing.JSpinner minJSpinner;
    private javax.swing.JCheckBox normalJCheckBox;
    private javax.swing.JCheckBox quietJCheckBox;
    private javax.swing.JCheckBox randomBufferSizeJCheckBox;
    private javax.swing.JCheckBox releaseJCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
