#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

REGDONE="@MVVM_HOME@/.regdone"
REGINFO="@MVVM_HOME@/registration.info"

afterReconfigure() {

    # Gotta wait a little whlie for the bridge to reconfigure
    sleep 5

    invoke-rc.d ntpdate restart
    invoke-rc.d ntp-server restart
    invoke-rc.d spamassassin restart
    invoke-rc.d rbot-mv restart

    if [ -f "$REGINFO" ]; then
        if [ ! -f "$REGDONE" -o "$REGDONE" -ot "$REGINFO" ]; then
            @PREFIX@/usr/bin/mvregister
        fi
    fi
}

## Execute these functions in a separate detached process, this way
## bunnicula doesn't wait around for us to run.
if [ $# -eq 0 ]; then
    ## Just append any arguments, they don't matter
    nohup sh @MVVM_HOME@/networking/after-reconfigure 1 2 >> @MVVM_LOG@/iptables.log 2>&1 &
else
    afterReconfigure
fi

exit 0
