#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@MVVM_HOME@/networking/functions

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

if [ $# -ne 6 ] && [ $# -ne 8 ]; then
    echo "USAGE: $0 <bridge> <inside> <insideAddress> <insideNetmask>"
    echo " <outside> [<outsideAddress> <outsideNetmask> <gateway>|${PUMP_FLAG}]"
    exit -1
fi

bridge=$1
inside=$2
insideAddress=$3
insideNetmask=$4
outside=$5
outsideAddress=$6
outsideNetmask=$7
gateway=$8

echo "Disabling bridge: ${bridge} to "
echo "  ${inside}: ${insideAddress}/${insideNetmask}"
echo "  ${outside}: ${outsideAddress} ${outsideNetmask} ${gateway}"

## Remove the bridge
deleteBridge ${bridge}

## Configure each of the interfaces
ifconfig ${inside}  ${insideAddress} netmask ${insideNetmask}

## XXXX May need to delete routes ????
 
## Delete all of the default gateways
for t in `route -n | grep "^0.0.0.0" | awk '{ print $2}'`; do 
    route del default gw $t
done

killPump

if [ $outsideAddress = ${PUMP_FLAG} ]; then 
    pump --script="" -i ${outside}
else
    ifconfig ${outside} ${outsideAddress} netmask ${outsideNetmask}
    route add default gw $gateway    
fi

