#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@MVVM_HOME@/networking/functions

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

if [ $# -ne 4 ] && [ $# -ne 6 ]; then
    echo "USAGE: $0 <bridge> <inside> <outside> [<bridgeAddress> <bridgeNetmask> <gateway>|${PUMP_FLAG}]"
    exit -1
fi

bridge=$1
inside=$2
outside=$3
bridgeAddress=$4
bridgeNetmask=$5
gateway=$6

echo "Enabling bridge: ${bridge} to ${bridgeAddress} ${bridgeNetmask} ${gateway}"

## Create the bridge
generateBridge ${bridge}

## First test to see if the bridge is already configured
if [ "$(getBridge ${inside})x" = "${bridge}x" ] && [ "$(getBridge ${outside})x" = "${bridge}x" ]; then
    if [ $bridgeAddress = ${PUMP_FLAG} ]; then 
        echo "Bridge is already configured, pumping interface."
        pump --script="" -i ${bridge}
        exit
    else
        if [ $(getAddresses $bridge) = ${bridgeAddress} ] && 
            [ $(getNetmasks $bridge) = ${bridgeNetmask} ]; then
            echo "Bridge is already configured."
            status=0
            
             ## kill pump and manually configure the address
            killPump
            ifconfig ${bridge} ${bridgeAddress} netmask ${bridgeNetmask}

            status=$?
            ## Delete all of the default routes
            for t in `route -n | grep "^0.0.0.0" | awk '{ print $2}'`; do route del default gw $t ; done
            ## Insert the new default route
            route add default gw $gateway

            exit ${status}
        fi
    fi    
fi


ifconfig ${inside} down
ifconfig ${outside} down

ifconfig ${inside} 0.0.0.0
ifconfig ${outside} 0.0.0.0

deleteBridge ${bridge}

brctl addbr ${bridge}
brctl addif ${bridge} ${inside}
brctl addif ${bridge} ${outside}

killPump

## XXX May need to delete all of the routes???

## Delete all of the default routes
for t in `route -n | grep "^0.0.0.0" | awk '{ print $2}'`; do route del default gw $t ; done

if [ $bridgeAddress = ${PUMP_FLAG} ]; then 
    pump -i ${bridge}
else
    ifconfig ${bridge} ${bridgeAddress} netmask ${bridgeNetmask}
    route add default gw $gateway
fi



