#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@MVVM_HOME@/networking/functions

## Interface to pump is the first argument.
intf=$1

## Interface index (used to assign an address if DHCP fails is)
intfIndex=$2

## The flags to pass to pump, use this to disable updating the resolv.conf and gateway
flags=$3

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

pumpInterface ${intf} ${intfIndex} ${flags}

true
