#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

## For the outside interface
RULE_CONFIG_FILE=@MVVM_HOME@/networking/rule-config
FUNCTIONS_FILE=@MVVM_HOME@/networking/functions

if [ -r ${RULE_CONFIG_FILE}  ]; then
    . ${RULE_CONFIG_FILE}
else
    echo "Unable to load the rule configuration file ${RULE_CONFIG_FILE}"
    exit -2
fi

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

echo "Renewing DHCP lease"

generateConfiguration

bridge=$(getBridge ${MVVM_OUTSIDE_INTF} )

## Make sure not to invoke the update script
if [ "${bridge}x" = "x" ]; then
    pump --script="" -i ${MVVM_OUTSIDE_INTF}
else
    pump --script="" -i ${bridge}
fi