#!/bin/sh

## These are for network configuration settings.
MVVM_NETWORK_PARAMS_FILE=@PREFIX@/usr/share/metavize/conf/networking.sh

## These are for parameters that can change during MVVM execution, eg enable DHCP forwarding
MVVM_TMP_PARAMS_FILE=@MVVM_CONF@/tmp_params

## These are parameters that rarely change, these are mostly items that are shared between
## the outside world and the mvvm (eg inside/outside)
MVVM_DEFAULTS_FILE=@PREFIX@/etc/default/mvvm

if [ -f ${MVVM_NETWORK_PARAMS_FILE} ]; then
    . ${MVVM_NETWORK_PARAMS_FILE}
else
    echo "File ${MVVM_NETWORK_PARAMS_FILE} not found."
fi

if [ -f ${MVVM_DEFAULTS_FILE} ] ; then
    . ${MVVM_DEFAULTS_FILE}
else
    echo "File ${MVVM_DEFAULTS_FILE} not found."
fi

if [ -f ${MVVM_TMP_PARAMS_FILE} ]; then
    . ${MVVM_TMP_PARAMS_FILE}
else
    echo "File ${MVVM_TMP_PARAMS_FILE} not found."
fi

## Local ports to antisubscribe to
ANTISUBSCRIBES_LOCAL_TCP_PORTS="22,443 80_inside"

## Possible for NAT(53) and 1194 for open vpn.
## XXX Look into only using open vpn on the outside ###
ANTISUBSCRIBES_LOCAL_UDP_PORTS="53,1194"

#### Handle all of the port guards

#### TCP Port guards
GUARD_OUTSIDE_TCP_PORTS=""
GUARD_INSIDE_TCP_PORTS=""

# disabled by default
if [ "${MVVM_ALLOW_OUT_HTTPS}x" = "truex" ]; then
    # not restricted by default
    if [ "${MVVM_ALLOW_OUT_RES}x" = "truex" -a "${MVVM_ALLOW_OUT_NET}x" != "x" ]; then
        if [ "${MVVM_ALLOW_OUT_MASK}x" = "x" ]; then
            GUARD_OUTSIDE_TCP_PORTS="${GUARD_OUTSIDE_TCP_PORTS} 443_$MVVM_ALLOW_OUT_NET"
        else
            GUARD_OUTSIDE_TCP_PORTS="${GUARD_OUTSIDE_TCP_PORTS} 443_$MVVM_ALLOW_OUT_NET/$MVVM_ALLOW_OUT_MASK"
        fi
    fi
else
    GUARD_OUTSIDE_TCP_PORTS="${GUARD_OUTSIDE_TCP_PORTS} 443"
fi

# enabled by default
if [ "x$MVVM_ALLOW_IN_HTTP" = "xfalse" ]; then
    GUARD_INSIDE_TCP_PORTS="${GUARD_INSIDE_TCP_PORTS} 80"
fi

# if in the build
if [ "x" != "x@PREFIX@" ] ; then
    GUARD_OUTSIDE_TCP_PORTS=""
    GUARD_INSIDE_TCP_PORTS=""
else
    ## When in the production environment, never antisubscribe to the outside
    ANTISUBSCRIBE_LOCAL_OUTSIDE=false
fi


## Port guards (always true)
GUARD_OUTSIDE_UDP_PORTS="53"

