#!/bin/sh

exec >> @MVVM_LOG@/iptables.log 2>&1

DEFAULT_HOSTNAME="edgeguard.local.domain"

## Function to set the hostname
function setHostname() {
    local l_hostname=$1
    local l_unqualified=${l_hostname/\.*}

    if [ -z ${l_hostname} ]; then
        echo "no hostname"
        return
    fi

    ## Save the hostname to etc hosts
    if [ "${l_unqualified}" != "${l_hostname}" ]; then
        sed -i -e "/127.0.0.1/d"  -e "2a 127.0.0.1  localhost" \
            -e "2a 127.0.0.1  ${l_unqualified} ${l_hostname}" \
            /etc/hosts
    else
        sed -i -e "/127.0.0.1/d"  -e "2a 127.0.0.1  localhost" \
            -e "2a 127.0.0.1  ${l_unqualified}" \
            /etc/hosts
    fi

    ## Set the hostname
    hostname ${l_hostname}

    ## Save to the hostname file
    echo "${l_hostname}" > /etc/hostname    
}

MVVM_HOSTNAME=${1:-${DEFAULT_HOSTNAME}}

## Set the hostname
setHostname ${MVVM_HOSTNAME}

true