#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

GLOBALS=@MVVM_HOME@/openvpn/globals

## Only required for servers
baseNotRequired="true"

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

${OPENVPN_SCRIPT} stop

## Openvpn is kind of a fickle program.
killall openvpn > /dev/null 2>&1

sleep .5

killall -KILL openvpn > /dev/null 2>&1

## This is always disabled so the server never starts at system startup.
disableOpenVPNStartup

true 
