#!/bin/sh

exec >> @MVVM_LOG@/wrapper.log 2>&1

## nothing to do
if [ -f /tmp/setup-wmi.exe ]; then 
    exit 0
fi
    

OPENSSL_CMD=openssl

BASE_DIR="@MVVM_HOME@/installers/wmimapper"

NSIS_SCRIPT="${BASE_DIR}/wmimapper-installer.nsi"

CNF_FILE="${BASE_DIR}/ssl.cnf"

KEY_FILE=`mktemp`
CRT_FILE=`mktemp`
CSR_FILE=`mktemp`

## Bit length of the RSA Key
BIT_LENGTH=2048

## How long the Key is valid for
KEY_LENGTH=3650

# Generate the SSL Server private key
${OPENSSL_CMD} genrsa -out ${KEY_FILE} ${BIT_LENGTH}

## Generate the CSR (required to self sign)
${OPENSSL_CMD} req -config ${CNF_FILE} -new -key ${KEY_FILE} -out ${CSR_FILE}

## Sign the CSR with the server key
${OPENSSL_CMD} x509 -in ${CSR_FILE} -out ${CRT_FILE} -req -signkey ${KEY_FILE} -days ${KEY_LENGTH}

## Create the installer
makensis -V1 -DKEY_FILE="${KEY_FILE}" -DCRT_FILE="${CRT_FILE}" ${NSIS_SCRIPT} > /dev/null

## Remove all of the trash
rm -f ${KEY_FILE}
rm -f ${CERT_FILE}
rm -f ${CSR_FILE}

true
