#! /bin/bash

exec >> @UVM_LOG@/openvpn.log 2>&1

GLOBALS=@UVM_HOME@/openvpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "[`date`,cleanup] Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

cleanPKI()
{
    ${RM_CMD} -rf '@UVM_CONF@/openvpn/pki'
    mkdir -p ${PKI_DIR}
}

cleanPackages()
{
    ${RM_CMD} -rf '@UVM_CONF@/openvpn/client-packages'
    mkdir -p ${PACKAGE_DIR}
}

cleanOpenvpn()
{
    ${RM_CMD} -rf '/etc/openvpn'
    mkdir -p ${OPENVPN_CONF_DIR}
    mkdir -p ${OPENVPN_DATA_DIR}
    mkdir -p ${OPENVPN_CCD_DIR}    
}

cleanMisc()
{
    ${RM_CMD} -rf '@UVM_CONF@/openvpn/misc'
    mkdir -p ${MISC_DIR}
}

cleanOpenvpn
cleanPackages
cleanPKI
cleanMisc

## Always make sure to disable the openvpn server
# Backup the initialization script
mv /etc/init.d/openvpn /etc/init.d/openvpn.tmp

# Disable openvpn startup at bootup
update-rc.d openvpn remove > /dev/null

# Restore the openvpn initialization script
mv /etc/init.d/openvpn.tmp /etc/init.d/openvpn


true

