#! /bin/bash

exec >> @UVM_LOG@/openvpn.log 2>&1

GLOBALS=@UVM_HOME@/openvpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

EMAIL_TEMPLATE="${DATA_DIR}/mail-template.html"
EG_TEMPLATE="${DATA_DIR}/eg-template.html"

commonName=`removeSpaces ${1}`
distributionKey=${2}
publicAddress=${3}
method=${4}
isEdgeGuard=${5}
siteName=${6}

## New branding variables
company="${7}"
companyUri="${8}"

## XXX May need to do some checks to see if files exists etc.

if [ -z "${commonName}" ]; then
    echo "Must specify a common name."
    exit -3
fi

if [ -z "${siteName}" ]; then
    echo "Must specify a site name."
    exit -3
fi

WIN_CONFIG_FILE=${PACKAGE_DIR}/client-${commonName}.ovpn
UNIX_CONFIG_FILE=${PACKAGE_DIR}/client-${commonName}.conf
CLI_CRT_FILE=${PKI_DIR}/client-${commonName}.crt
CLI_KEY_FILE=${PKI_DIR}/client-${commonName}.key

NSI_SCRIPT=${DATA_DIR}/installer/openvpn-gui.nsi

## Create the output directory
mkdir -p ${PACKAGE_DIR}

## Create a tempory directory for the client
buildConfigFile() {
    local tmpDir=`mktemp -d || exit -3`

    ## Done this way so the zip directory is called
    local outputDir="${tmpDir}/${ZIP_BASE}"
    local keyDir="${outputDir}/${ZIP_BASE}"

    mkdir ${outputDir} || exit -4
    mkdir ${keyDir} || exit -4
    
    cp ${UNIX_CONFIG_FILE} ${outputDir}/${siteName}.conf
    cp ${WIN_CONFIG_FILE}  ${outputDir}/${siteName}.ovpn
    cp ${CLI_KEY_FILE}     ${keyDir}/${siteName}-${commonName}.key
    cp ${CLI_CRT_FILE}     ${keyDir}/${siteName}-${commonName}.crt
    cp ${CA_CRT}           ${keyDir}/${siteName}-ca.crt

    pushd ${tmpDir}
    ## Remove the zip first, otherwise it will append files.
    rm -f ${PACKAGE_DIR}/config-${commonName}.zip
    zip -r ${PACKAGE_DIR}/config-${commonName}.zip ${ZIP_BASE} > /dev/null
    popd

    ## Clean up
    ${RM_CMD} -f ${outputDir}/${siteName}.conf
    ${RM_CMD} -f ${outputDir}/${siteName}.ovpn
    ${RM_CMD} -f ${keyDir}/${siteName}-${commonName}.key
    ${RM_CMD} -f ${keyDir}/${siteName}-${commonName}.crt
    ${RM_CMD} -f ${keyDir}/${siteName}-ca.crt
    
    rmdir ${keyDir}
    rmdir ${outputDir}
    rmdir ${tmpDir}
}

buildEmail()
{
    local t_emailFile="${PACKAGE_DIR}/mail-${commonName}.eml"
    local t_mailTemplate=${EMAIL_TEMPLATE}
    
    local t_externalAddress
    
    if [ "${isEdgeGuard}x" = "truex" ]; then
        t_mailTemplate=${EG_TEMPLATE}
    fi

    sed -e "s|%%KEY%%|${distributionKey}|g" \
        -e "s|%%ADDRESS%%|${publicAddress}|g" \
        -e "s|%%COMPANY%%|${company}|g" \
        -e "s|%%COMPANY_URI%%|${companyUri}|g" \
        ${t_mailTemplate} > ${t_emailFile}
}

## Convert the client file to dos
unix2dos ${WIN_CONFIG_FILE}

## Run NSIS to create client distro.
makensis -V1 -DCOMMON_NAME="${commonName}" -DSITE_NAME="${siteName}" ${NSI_SCRIPT} > /dev/null

buildConfigFile

case "${method}" in
    "email")
        echo "[`date`,generate-distro] Distributing over email"
        buildEmail
        ;;
    *)
        echo "[`date`,generate-distro] ignoring method ${method}"
esac

true

