#! /bin/bash

exec >> @UVM_LOG@/openvpn.log 2>&1

GLOBALS=@UVM_HOME@/openvpn/globals

baseNotRequired="true"

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

## Number of times to wait for the Open vpn server to start
RETRY_ATTEMPTS=15
TEST_DELAY=1
TEST_FAILED=-5
DOWNLOAD_ERROR=-6
MISSING_FILE_ERROR=-7
ERROR_INTERNAL=-8

## Amount of time to spend on each download
DOWNLOAD_TIMEOUT=6

## Number of times to retry ( 5 times at 6 seconds, 30 seconds)
DOWNLOAD_RETRIES=5

method=${1}
serverAddress=${2}
localPath="${2}"
distributionKey=${3}

mkdir -p ${PACKAGE_DIR}
mkdir -p ${MISC_DIR}

# If the tun device doesn't exist, then create it
TUN_DEVICE=/dev/net/tun
if [ ! -c ${TUN_DEVICE} ]; then
    mkdir -p /dev/net
    mknod ${TUN_DEVICE} c 10 200
fi

destination=`mktemp || exit ${MISSING_FILE_ERROR}`

logFile=@UVM_LOG@/openvpn.log

copyLocalFile()
{
    if [ !-f "${localPath}" ]; then
        echo "Unable to find the file: ${localPath}"
        exit ${MISSING_FILE_ERROR}
    fi

    cp "${localPath}" "${destination}"
}

downloadClient()
{
    curl -f -v -k --max-time ${DOWNLOAD_TIMEOUT} \
        --retry ${DOWNLOAD_RETRIES} -o ${destination} \
        "https://${serverAddress}/openvpn/config.zip?key=${distributionKey}" \
        || exit ${DOWNLOAD_ERROR}
}

installClient()
{
    local t_output=`mktemp -d || exit -3`
    
    unzip ${destination} -d ${t_output} || ( ${RM_CMD} -rf ${t_output};  exit -4 )
    
    ## Cleanup the old files
    ## A little risky, but hey
    rm -rf /etc/openvpn
    mkdir -p /etc/openvpn || ( ${RM_CMD} -rf ${t_output};  exit -4 )

    ## Copy in the necessary files
    cp ${t_output}/untangle-vpn/*.conf ${OPENVPN_CONF_DIR}/client.conf \
        || ( ${RM_CMD} -rf ${t_output};  exit -4 )

    ## Update the configuration file to log to a normal place
    sed -i -e "\$a log-append ${logFile}" ${OPENVPN_CONF_DIR}/client.conf 

    cp -r ${t_output}/untangle-vpn/untangle-vpn ${OPENVPN_CONF_DIR}/untangle-vpn \
        || ( ${RM_CMD} -f ${OPENVPN_CONF_DIR}/client.conf ; ${RM_CMD} -rf ${t_output};  exit -4 )
    
    ## Cleanup
    ${RM_CMD} -rf ${t_output}
}

testInstall()
{
    /etc/init.d/openvpn start
    local t
    local t_success

    for (( t = 0 ; t < ${RETRY_ATTEMPTS} ; t++ )); do
        if [ -n "`grep \"Initialization Sequence Completed\" ${logFile}`" ]; then
            t_success="true"
            break;
        fi

        sleep ${TEST_DELAY}
    done
    
    ## Stop the server
    bash ${SCRIPT_DIR}/stop-openvpn

    if [ -z "${t_success}" ]; then
        echo "Unable to start server"
        exit ${TEST_FAILED}
    else
        echo "Succesfully started server"
    fi
}

completeInstall()
{
    ## Modify the startup script to run a command to update the route after startup
    sed  -i -e "\$ a route-up \"bash ${SCRIPT_DIR}/route-up\"" ${OPENVPN_CONF_DIR}/client.conf
}

case "${method}" in
    "local")
        copyLocalFile
        ;;
    
    "email")
        downloadClient
        ;;
    
    *)
        echo "Unknown method '${method}'"
        exit ${ERROR_INTERNAL}
        ;;
esac

installClient

testInstall

completeInstall

true
