#!/bin/sh

exec >> @UVM_LOG@/openvpn.log 2>&1

currentPid=`pidof openvpn`
expectedPid=`cat /var/run/openvpn.client.pid`

if [ -z "${currentPid}" ] || [ "${currentPid}x" != "${expectedPid}x" ]; then
    echo -e "\n[DEBUG:`date`] OpenVPN is no longer running, attempting a restart"
    killall openvpn
    /etc/init.d/openvpn restart
fi

echo -n "."

## Test if the UVM is aware of the VPN interface
currentYear=`date +"%y"`
lastError=`tail -n 100 @UVM_LOG@/console.log | grep 'netcap_intf_db.c:[0-9]*:CRITICAL ERROR: Nothing is known about' | awk  -F '.'  '{ print $1 }' | tail -n 1  | sed "s|^\(..\)-\(..\)|\1/\2/${currentYear}|"`

if [ "${lastError}x" != "x" ] && (( `date -d "${lastError}" +%s` > ( `date +%s` - 60 ))) ; then
   echo -e "\n[DEBUG:`date`] Running mcli updateAddress to renew interfaces ${lastError}"
   @USR_BIN@/mcli updateAddress
fi

true

