#! /bin/bash

exec >> @UVM_LOG@/openvpn.log 2>&1

GLOBALS=@UVM_HOME@/openvpn/globals

baseNotRequired="true"

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

## This is where to write the listing of all of the client files
destination="${MISC_DIR}/client-list"

listUsb()
{
    local t_usbDevice=`lookup_usb_device`
    
    if [ -z "${t_usbDevice}" ]; then
        echo "Unable to find USB device"
        exit -${USB_ERROR}
    fi
    
    echo "Mounting device ${t_usbDevice}"
    
    local t_mountPoint=`mktemp -d || exit -3`
    
    ## Attempt to mount the usb key {dev}
    mount "${t_usbDevice}" ${t_mountPoint} || usbCleanup ${t_mountPoint} ${USB_ERROR}

    mkdir -p `dirname ${destination}` || usbCleanup ${t_mountPoint} ${USB_ERROR}

    ## List out the files, only show the files with the stamp for eg.
    ls -1 ${t_mountPoint}/${USB_DEST}/config-*.zip  ${t_mountPoint}/${USB_DEST}/eg-*.stamp \
        | sed -e 's|.*config-\(.*\).zip|\1|' -e 's|.*eg-\(.*\).stamp|\1|' | sort | uniq -d \
        > ${destination}

    
    
    ## Cleanup
    usbCleanup ${t_mountPoint}
}


listUsb


