#! /bin/bash

exec >> @UVM_LOG@/openvpn.log 2>&1

## Sleep a little while
sleep 1

@PREFIX@/usr/bin/ucli refreshNetworkConfig

/etc/init.d/untangle-net-alpaca-iptables restart openvpn-route-up

true

