#!/bin/dash

# If openvpn is running - restart it
if [ ! -z "`pidof openvpn`" ] ; then
    /etc/init.d/openvpn restart
fi

# HUP doesnt seem to work - openvpn dies on startup
# killall -HUP openvpn 2>/dev/null

# Rewrite status files
/usr/share/untangle-netd/bin/write-interface-status.py -I tun0 -i 250 -w /var/lib/untangle-netd/interface-250-status.js
if [ ! -f /var/lib/untangle-netd/interface-250-status.js ] ; then
    echo "Missing status file: /var/lib/untangle-netd/interface-250-status.js"
fi
/usr/share/untangle-netd/bin/write-interface-status.py -I tun0 -i 250 -w /var/lib/untangle-netd/interface-tun0-status.js
if [ ! -f /var/lib/untangle-netd/interface-tun0-status.js ] ; then
    echo "Missing status file: /var/lib/untangle-netd/interface-tun0-status.js"
fi
