#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

GLOBALS=@MVVM_HOME@/openvpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

commonName=`removeSpaces $1`

## XXX May need to do some checks to see if files exists etc.

if [ -z "${commonName}" ]; then
    echo "Must specify a common name"
    exit -3
fi

OPENVPN_CONF_DIR=@MVVM_CONF@/openvpn
OUTPUT_DIRECTORY=${OPENVPN_CONF_DIR}/client-packages
WIN_CONFIG_FILE=${OPENVPN_CONF_DIR}/client-${commonName}.ovpn
UNIX_CONFIG_FILE=${OPENVPN_CONF_DIR}/client-${commonName}.conf
CLI_CRT_FILE=${OPENVPN_CONF_DIR}/client-${commonName}.crt
CLI_KEY_FILE=${OPENVPN_CONF_DIR}/client-${commonName}.key

NSI_SCRIPT=${OPENVPN_HOME}/installer/openvpn-gui.nsi

## Create the output directory
mkdir -p ${OUTPUT_DIRECTORY}

## Create a tempory directory for the client
function buildConfigFile() {
    local tmpDir=`mktemp -d || exit -3`

    ## Done this way so the zip directory is called office-mv
    local outputDir="${tmpDir}/office-mv"
    local keyDir="${outputDir}/metavize-data"

    mkdir ${outputDir} || exit -4
    mkdir ${keyDir} || exit -4
    
    cp ${UNIX_CONFIG_FILE} ${outputDir}/office-mv.conf
    cp ${WIN_CONFIG_FILE}  ${outputDir}/office-mv.ovpn
    cp ${CLI_KEY_FILE}     ${keyDir}/${commonName}.crt
    cp ${CLI_CRT_FILE}     ${keyDir}/${commonName}.key
    cp ${CA_CRT}           ${keyDir}/ca.crt

    pushd ${tmpDir}
    zip -r ${OUTPUT_DIRECTORY}/config-${commonName}.zip office-mv
    popd

    ## Clean up
    rm -f ${outputDir}/office-mv.conf
    rm -f ${outputDir}/office-mv.ovpn
    rm -f ${keyDir}/${commonName}.crt
    rm -f ${keyDir}/${commonName}.key
    rm -f ${keyDir}/ca.crt
    
    rmdir ${keyDir}
    rmdir ${outputDir}
    rmdir ${tmpDir}
}

## Convert the client file to dos
unix2dos ${WIN_CONFIG_FILE}

## Run NSIS to create client distro.
makensis -V1 -DCOMMON_NAME="${commonName}" ${NSI_SCRIPT}

buildConfigFile

true

