#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

GLOBALS=@MVVM_HOME@/openvpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

EMAIL_TEMPLATE="${DATA_DIR}/mail-template.html"
EG_TEMPLATE="${DATA_DIR}/eg-template.html"

commonName=`removeSpaces ${1}`
distributionKey=${2}
publicAddress=${3}
distributeUsb=${4}
isEdgeGuard=${5}
siteName=${6}

## XXX May need to do some checks to see if files exists etc.

if [ -z "${commonName}" ]; then
    echo "Must specify a common name."
    exit -3
fi

if [ -z "${siteName}" ]; then
    echo "Must specify a site name."
    exit -3
fi

WIN_CONFIG_FILE=${PACKAGE_DIR}/client-${commonName}.ovpn
UNIX_CONFIG_FILE=${PACKAGE_DIR}/client-${commonName}.conf
CLI_CRT_FILE=${PKI_DIR}/client-${commonName}.crt
CLI_KEY_FILE=${PKI_DIR}/client-${commonName}.key

NSI_SCRIPT=${DATA_DIR}/installer/openvpn-gui.nsi

## Create the output directory
mkdir -p ${PACKAGE_DIR}

## Create a tempory directory for the client
function buildConfigFile() {
    local tmpDir=`mktemp -d || exit -3`

    ## Done this way so the zip directory is called office-mv
    local outputDir="${tmpDir}/${ZIP_BASE}"
    local keyDir="${outputDir}/${ZIP_BASE}"

    mkdir ${outputDir} || exit -4
    mkdir ${keyDir} || exit -4
    
    cp ${UNIX_CONFIG_FILE} ${outputDir}/${siteName}.conf
    cp ${WIN_CONFIG_FILE}  ${outputDir}/${siteName}.ovpn
    cp ${CLI_KEY_FILE}     ${keyDir}/${siteName}-${commonName}.key
    cp ${CLI_CRT_FILE}     ${keyDir}/${siteName}-${commonName}.crt
    cp ${CA_CRT}           ${keyDir}/${siteName}-ca.crt

    pushd ${tmpDir}
    zip -r ${PACKAGE_DIR}/config-${commonName}.zip ${ZIP_BASE} > /dev/null
    popd

    ## Clean up
    ${RM_CMD} -f ${outputDir}/${siteName}.conf
    ${RM_CMD} -f ${outputDir}/${siteName}.ovpn
    ${RM_CMD} -f ${keyDir}/${siteName}-${commonName}.key
    ${RM_CMD} -f ${keyDir}/${siteName}-${commonName}.crt
    ${RM_CMD} -f ${keyDir}/${siteName}-ca.crt
    
    rmdir ${keyDir}
    rmdir ${outputDir}
    rmdir ${tmpDir}
}

function buildEmail()
{
    local t_emailFile="${PACKAGE_DIR}/mail-${commonName}.eml"
    local t_mailTemplate=${EMAIL_TEMPLATE}
    
    local t_externalAddress
    
    if [ "${isEdgeGuard}x" = "truex" ]; then
        t_mailTemplate=${EG_TEMPLATE}
    fi

    sed -e "s|%%KEY%%|${distributionKey}|g" \
        -e "s|%%ADDRESS%%|${publicAddress}|g" \
        ${t_mailTemplate} > ${t_emailFile}
}

function copyToUsb()
{
    local t_usbDevice=`lookupUsbDevice`
    ## Unique qualifier to distinguish the file on the USB key
    local fileKey="${siteName}-${commonName}"
    
    if [ -z "${t_usbDevice}" ]; then
        echo "Unable to find USB device"
        exit -${USB_ERROR}
    fi

    ## Attempt to mount the usb key
    echo "Mounting device ${t_usbDevice}"

    local t_mountPoint=`mktemp -d || exit -3`
    
    mount "${t_usbDevice}" ${t_mountPoint} || usbCleanup ${t_mountPoint} ${USB_ERROR}
    
    mkdir -p ${t_mountPoint}/${USB_DEST}/ || usbCleanup ${t_mountPoint} ${USB_ERROR}

    cp -f ${PACKAGE_DIR}/config-${commonName}.zip \
        ${t_mountPoint}/${USB_DEST}/config-${fileKey}.zip || usbCleanup ${t_mountPoint} ${USB_ERROR}

    cp -f ${PACKAGE_DIR}/setup-${commonName}.exe \
        ${t_mountPoint}/${USB_DEST}/setup-${fileKey}.exe || usbCleanup ${t_mountPoint} ${USB_ERROR}

    # A stamp which indicates whether or not this client is an edgeguard
    if [ "${isEdgeGuard}x" = "truex" ]; then
        touch ${t_mountPoint}/${USB_DEST}/eg-${fileKey}.stamp || usbCleanup ${t_mountPoint} ${USB_ERROR}
    else
        rm -f ${t_mountPoint}/${USB_DEST}/eg-${fileKey}.stamp || usbCleanup ${t_mountPoint} ${USB_ERROR}
    fi
    
    ## Cleanup
    usbCleanup ${t_mountPoint}
}

## Convert the client file to dos
unix2dos ${WIN_CONFIG_FILE}

## Run NSIS to create client distro.
makensis -V1 -DCOMMON_NAME="${commonName}" -DSITE_NAME="${siteName}" ${NSI_SCRIPT} > /dev/null

buildConfigFile

if [ "${distributeUsb}x" = "truex" ]; then
    echo "Copying configuration to USB"
    copyToUsb
else
    echo "Distributing over email"
    buildEmail
fi

true

