#!/bin/sh

OPENVPN_HOME=@MVVM_HOME@/openvpn
BASE_CONFIG_FILE=@MVVM_CONF@/openvpn_base_cfg

## There must be a configuration file 
if [ -r ${BASE_CONFIG_FILE} ]; then
    . ${BASE_CONFIG_FILE}
else
    echo "Unable to load the openvpn configuration file ${BASE_CONFIG_FILE}"
    exit -2
fi

## This is where all of the keys (client and server) are generated.
export KEY_GEN_DIR=@MVVM_CONF@/openvpn
export INDEX_FILE=${KEY_GEN_DIR}/index.txt
export SERIAL_FILE=${KEY_GEN_DIR}/serial

## This is the client status file that java uses to check the certificate status for each client
CLIENT_STATUS_FILE="${KEY_GEN_DIR}/client_status.txt"

## Default parameters and file locations for the certificates
OPENSSL="opensslDbg"

OPENSSL_CFG_FILE="${OPENVPN_HOME}/openssl.cnf"
CA_KEY="${KEY_GEN_DIR}/ca.key"
CA_CRT="${KEY_GEN_DIR}/ca.crt"

## This is where all of the server parameters are placed.
BASE_DIR=/etc/openvpn
KEY_DIR=${BASE_DIR}/keys

## Issuing ten year certs
CERT_DURATION=3650

## Client configuration directory
CLIENT_CFG_DIR="${BASE_DIR}/ccd"

## dnQualifier for the different certs
DN_QUALIFIER_SERVER="server"
DN_QUALIFIER_CLIENT="client"
DN_QUALIFIER_CA="certificateAuthority"

## Debugging function
function opensslDbg()
{
    echo openssl $@
    openssl $@
}

function validateUsbKey()
{
############################# XXXXXXXXXXXXXXXXXXXXXXXXXX
    true
}

function saveToUsbKey()
{
############################# XXXXXXXXXXXXXXXXXXXXXXXXXX
    true
}

function removeSpaces() {
    ## don't know why but this works, and just 'echo ${*// /_}' doesn't.
    local val="$*"
    echo ${val// /_}
}

function getSerialNumber() {
    local crt=${1}

    grep "Serial Number" ${crt} | sed 's/.*(0x\([^(]*\)).*/\1/g'
}

function isRevoked()
{
    local commonName="${1}"
    local clientCrt=`getClientCrtFile ${commonName}`
    
    ## If the cert is there, it hasn't been revoked, (it is renamed after being revoked)
    if [ -f ${clientCrt} ]; then
        return
    fi
    
    ## If there are any cert-revoked files, then the cert has been revoked.
        
    local search=`grep '^R' ${INDEX_FILE} | grep "CN=${commonName}"`

    if [ -n "${search}" ]; then echo "true" ; fi
}

function getClientCrtFile()
{
    echo "${KEY_GEN_DIR}/client-${1}.crt"
}

function getClientKeyFile()
{
    echo "${KEY_GEN_DIR}/client-${1}.key"
}

## XXXX This function isn't used anymore
function getClientRevokedCrtFile()
{
    local commonName="${1}"
    local clientCrt=`getClientCrtFile ${commonName}`
    local serialNumber=`getSerialNumber ${clientCrt}`
    echo "${KEY_GEN_DIR}/client-revoked-${commonName}-${serialNumber}.crt"
}

## Write a new client status file which java uses to check the status of each client
function updateClientStatus()
{
    ## Delete any line that has a dnQualifier for the server
    sed -e "/dnQualifier=${DN_QUALIFIER_SERVER}/d" -e 's/^\(R\|V\).*\/CN=\([^/]*\).*/\1 \2/' ${INDEX_FILE} | uniq > ${CLIENT_STATUS_FILE}
}