#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

commonName="$1"

GLOBALS=@MVVM_HOME@/vpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${BASE_CONFIG_FILE}"
    exit -2
fi



validateBase() {
    if [ "${commonName}x" = "x" ]; then
        echo "Must specify a common name for the key"
        exit -3
    fi
    
    ## Also have to check the ca.crt and the ca.key
    if [ ! -d ${KEY_GEN_DIR} ] || [ ! -d ${KEY_DIR} ] || [ ! -f ${INDEX_FILE} ] || 
        [ ! -f ${SERIAL_FILE} ]; then
        echo "The base is not currently initialized"
        exit -4
    fi
}

function revokeClient()
{
    local clientCrl=`mktemp`
    local revokeTest=`mktemp`
    local clientCrt="${KEY_GEN_DIR}/client-${commonName}.crt"

    export COMMON_NAME=${commonName}

    # revoke key and generate a new CRL
    ${OPENSSL} ca -revoke ${clientCrt} -config ${OPENSSL_CFG_FILE}
    
    # generate a new CRL
    ${OPENSSL} ca -gencrl -out ${clientCrl} -config ${OPENSSL_CFG_FILE}
    cat ${CA_CRT} ${clientCrl} >${revokeTest}
    
    # verify the revocation
    ${OPENSSL} verify -CAfile ${revokeTest} -crl_check ${clientCrt}

    rm -f ${clientCrl}
    rm -f ${revokeTest}
}

## Check for the USB key if necessary
validateUsbKey

## Validate that the base has been generated
validateBase

## Generate the client key
revokeClient




