#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

GLOBALS=@MVVM_HOME@/openvpn/globals

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

RETRY_ATTEMPTS=5
RESTART_DELAY=1

## XXX May need to run reconfiguration for the bridge
## 

## Use restart just in case there is one lingering around
## For some reason "restart" is different stop then start
${OPENVPN_SCRIPT} stop

## Let the dust settle
sleep .5

## Just in case, kill all openvpn instances
killall openvpn > /dev/null 2>&1 

sleep .5

echo "Starting the openvpn server"

## This is required or else openvpn won't restart properly (sometimes the UDP port is still bound)
for (( t = 0 ; t < ${RETRY_ATTEMPTS} ; t++ )); do
    ## There script doesn't actually return -1
    [ -z "`${OPENVPN_SCRIPT} start | grep FAILED`" ] && true && break
    echo "unable to start openvpn daemon, waiting ${RESTART_DELAY} seconds"

    ## Just in case, kill all openvpn instances
    killall openvpn > /dev/null 2>&1 

    sleep ${RESTART_DELAY}
    
    ## Indicate the script failed if it never starts
    false
done
