#!/bin/sh

exec >> @MVVM_LOG@/openvpn.log 2>&1

GLOBALS=@MVVM_HOME@/openvpn/globals

## Only required for servers
baseNotRequired="true"

## There must be a configuration file 
if [ -r ${GLOBALS} ]; then
    . ${GLOBALS}
else
    echo "Unable to load the openvpn configuration file ${GLOBALS}"
    exit -2
fi

RETRY_ATTEMPTS=5
RESTART_DELAY=1


TUN_DEVICE=/dev/net/tun

# If the tun device doesn't exist, then create it
if [ ! -c ${TUN_DEVICE} ]; then
    mkdir -p /dev/net
    mknod ${TUN_DEVICE} c 10 200
fi

## This is always disabled so the server never starts at system startup.
disableOpenVPNStartup

## XXX May need to run reconfiguration for the bridge
## 

## Update legacy clients to use the new configuration
OPENVPN_CLIENT=/etc/openvpn/client.conf
if [ -f ${OPENVPN_CLIENT} ]; then
    sed -i -e 's|^route-up /usr/share/metavize/openvpn/route-up$|route-up "sh /usr/share/metavize/openvpn/route-up"|'  ${OPENVPN_CLIENT} 

    if [ -z "`grep keepalive ${OPENVPN_CLIENT}`" ]; then
        echo "keepalive 10 120" >> ${OPENVPN_CLIENT}
    fi
fi

## Use restart just in case there is one lingering around
## For some reason "restart" is different stop then start
${OPENVPN_SCRIPT} stop

## Let the dust settle
sleep .5

## Just in case, kill all openvpn instances
killall openvpn > /dev/null 2>&1 

sleep .5

echo "Starting the openvpn server"

## This is required or else openvpn won't restart properly (sometimes the UDP port is still bound)
for (( t = 0 ; t < ${RETRY_ATTEMPTS} ; t++ )); do
    ## These script don't return a non-zero value
    [ -z "`${OPENVPN_SCRIPT} start | grep FAILED`" ] && true && break
    echo "unable to start openvpn daemon, waiting ${RESTART_DELAY} seconds"

    ## Just in case, kill all openvpn instances
    killall openvpn > /dev/null 2>&1 

    sleep ${RESTART_DELAY}
    
    ## Indicate the script failed if it never starts
    false
done
