#!/bin/sh

tran_name=$1
rep_base=$2
period=$3
generate_email_index=$4

base_dir=@UVM_REPORTS@/current
tran_dir=${base_dir}/${tran_name}

ORG_PWD=`pwd`
NEW_PWD=$tran_dir
cd $NEW_PWD

## Parameters:
## <estat> : exit status
## <src> : source of error
function exitOnUvmError()
{
    local t_estat=$1
    local t_src=$2
    if [ $t_estat != 0 ]; then
        echo $t_src "error, exit status:" $t_estat
        cd $OLD_PWD
        exit $t_estat
    fi
}

if [ -f name ]; then
    # note that index-reports uses content of node name file to create anchor point on index html page
    TNAME=`cat name`
    REPNAME=`echo $TNAME User Summary`
    base_name=${rep_base}--${period}.html

    if [ "$period" = daily ]; then
        AHREFVAL=../index.html#${TNAME}
    elif [ "$period" = weekly ]; then
        AHREFVAL=../index_online_weekly.html#${TNAME}
    elif [ "$period" = monthly ]; then
        AHREFVAL=../index_online_monthly.html#${TNAME}
    fi
else
    echo "error, node has no name"
    cd $OLD_PWD
    exit 1
fi

base_file=${tran_dir}/${base_name}

REPDATE=`/bin/date -d'yesterday' +'%A %B %e, %Y'`
REPPERIOD=`echo $period $REPDATE`

generate_page ()
{
cat > $base_file <<EOF
<!-- header -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <link href="../css/main.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <table cellspacing="0" cellpadding="0" border="0" align="center" class="main">
      <tbody>
        <tr>
          <td class="main-top">
          </td>
        </tr>
        <tr>
          <td class="main-middle">
            <div align=center>
            <a href="$AHREFVAL"><font face="SansSerif" size="-1">back</font></a>
            </div>

<!-- top banner -->
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr><td width="50%">&nbsp;</td><td align="center">

<a name="JR_PAGE_ANCHOR_0_1"/>
<table style="width: 612px" cellpadding=0 cellspacing=0 border=0>
<tr>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td><img src="../images/px" style="width: 53px; height: 1px"></td>
  <td><img src="../images/px" style="width: 43px; height: 1px"></td>
  <td><img src="../images/px" style="width: 4px; height: 1px"></td>
  <td><img src="../images/px" style="width: 69px; height: 1px"></td>
  <td><img src="../images/px" style="width: 3px; height: 1px"></td>
  <td><img src="../images/px" style="width: 38px; height: 1px"></td>
  <td><img src="../images/px" style="width: 5px; height: 1px"></td>
  <td><img src="../images/px" style="width: 7px; height: 1px"></td>
  <td><img src="../images/px" style="width: 12px; height: 1px"></td>
  <td><img src="../images/px" style="width: 42px; height: 1px"></td>
  <td><img src="../images/px" style="width: 21px; height: 1px"></td>
  <td><img src="../images/px" style="width: 53px; height: 1px"></td>
  <td><img src="../images/px" style="width: 116px; height: 1px"></td>
  <td><img src="../images/px" style="width: 3px; height: 1px"></td>
  <td><img src="../images/px" style="width: 50px; height: 1px"></td>
  <td><img src="../images/px" style="width: 12px; height: 1px"></td>
  <td><img src="../images/px" style="width: 41px; height: 1px"></td>
  <td><img src="../images/px" style="width: 1px; height: 1px"></td>
  <td><img src="../images/px" style="width: 19px; height: 1px"></td>
</tr>
<tr valign=top>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 24px"></td>
  <td colspan=2 rowspan=9><img src="/images/BrandingLogo.gif" border=0 style="width: 150px; height: 96px"></td>
  <td colspan=17><img src="../images/px" style="width: 496px; height: 24px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 6px"></td>
  <td><img src="../images/px" style="width: 4px; height: 6px"></td>
  <td colspan=3 rowspan=2><span style="font-family: SansSerif; font-size: 18.0px;"></span></td>
  <td colspan=13><img src="../images/px" style="width: 382px; height: 6px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 17px"></td>
  <td><img src="../images/px" style="width: 4px; height: 17px"></td>
  <td><img src="../images/px" style="width: 5px; height: 17px"></td>
  <td colspan=10 rowspan=2 style="text-align: right;"><span style="font-family: SansSerif; font-size: 14.0px;">$REPNAME</span></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 17px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td colspan=5><img src="../images/px" style="width: 119px; height: 1px"></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 1px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td colspan=17><img src="../images/px" style="width: 496px; height: 1px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td><img src="../images/px" style="width: 4px; height: 1px"></td>
  <td colspan=3 rowspan=3><span style="font-family: SansSerif; font-size: 18.0px;"></span></td>
  <td colspan=13><img src="../images/px" style="width: 382px; height: 1px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td><img src="../images/px" style="width: 4px; height: 13px"></td>
  <td><img src="../images/px" style="width: 5px; height: 13px"></td>
  <td colspan=10 style="text-align: right;"><span style="font-family: SansSerif; font-size: 10.0px;">$REPPERIOD</span></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 13px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 9px"></td>
  <td><img src="../images/px" style="width: 4px; height: 9px"></td>
  <td colspan=13><img src="../images/px" style="width: 382px; height: 9px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 24px"></td>
  <td colspan=17><img src="../images/px" style="width: 496px; height: 24px"></td>
</tr>
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 5px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td colspan=17 bgcolor=#000000><img src="../images/px" border=0></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 1px"></td>
</tr>
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 4px"></td>
</tr>

<!-- content -->
<tr valign=top>
  <td colspan=1><img src="../images/px" style="width: 20px; height: 14px"></td>
  <td colspan=9 style="text-align: left;"><span style="font-family: SansSerif; font-size: 10.0px; font-weight: bold;">Summary Reports</span></td>
  <td colspan=11><img src="../images/px" style="width: 370px; height: 14px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px; font-style: italic;">User</span></td>
</tr>

<!-- user content (start) -->
EOF

    generate_user_content_area

# add separater
cat >> $base_file <<EOF
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 5px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td colspan=17 bgcolor=#000000><img src="../images/px" border=0></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 1px"></td>
</tr>
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 5px"></td>
</tr>

<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px; font-style: italic;">Client</span></td>
</tr>
EOF

    generate_hname_content_area

cat >> $base_file <<EOF
<!-- user content (end) -->

<!-- bottom banner -->
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 9px"></td>
</tr>
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 1px"></td>
  <td colspan=17 bgcolor=#000000><img src="../images/px" border=0></td>
  <td colspan=2><img src="../images/px" style="width: 20px; height: 1px"></td>
</tr>
<tr valign=top>
  <td colspan=20><img src="../images/px" style="width: 612px; height: 5px"></td>
</tr>
</table>

</td><td width="50%">&nbsp;</td></tr>
</table>

<!-- footer -->
            <div align=center>
            <a href="$AHREFVAL"><font face="SansSerif" size="-1">back</font></a>
            </div>
          </td>
        </tr>
        <tr>
          <td class="main-bottom">
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
EOF
}

generate_user_content_area ()
{
    local ucnt=0

    while read line
    do
        if [ "${line}" = "" ]; then
            # skip blank lines
            continue
        fi

        local UNAME_FN=$(echo ${line} | cut -d' ' -f1)
        local UNAME=$(echo ${line} | cut -d' ' -f2-)
        local UNAMESUM_HTML=`echo ${rep_base}--${UNAME_FN}--${period}.html`
        local UNAMESUM_PDF=`echo ${rep_base}--${UNAME_FN}--${period}.pdf`

        # XXX hack
        # if this report has any data associated with this username,
        # it'll contain the ">100%<" char sequence (at least one copy)
        # (this test also implicitly checks that the html/pdf reports exists)
        # grep exit status: 0=match, 1=no match, 2=error (no file)
        grep ">100%<" ${tran_dir}/${UNAMESUM_HTML} > /dev/null 2>&1
        local gstat=$?
        if [ $gstat == 1 ]; then
            # no data
            rm -f ${tran_dir}/${UNAMESUM_HTML}
            rm -f ${tran_dir}/${UNAMESUM_PDF}
            continue
        elif [ $gstat == 2 ]; then
            # no file
            continue
        fi

        if [ "$generate_email_index" = true ]; then

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px;">$UNAME</span></td>
  <td colspan=6><span style="font-family: SansSerif; font-size: 9.0px; text-align: right">(<a href="$UNAMESUM_PDF">PDF</a>)&nbsp;</span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

        else

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px;">$UNAME</span></td>
  <td colspan=6><span style="font-family: SansSerif; font-size: 9.0px; text-align: right">(<a href="$UNAMESUM_HTML">HTML</a> | <a href="$UNAMESUM_PDF">PDF</a>)&nbsp;</span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

        fi

        ucnt=$((ucnt+1))

    done < $base_dir/uname.lst

    if (( ucnt == 0 )); then

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=12><span style="font-family: SansSerif; font-size: 9.0px;">
  &lt;No user events were detected during this time period.&gt;
  </span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

    fi
}

generate_hname_content_area ()
{
    local hcnt=0

    while read line
    do
        if [ "${line}" = "" ]; then
            # skip blank lines
            continue
        fi

        local HNAME_FN=$(echo ${line} | cut -d' ' -f1)
        local HNAME=$(echo ${line} | cut -d' ' -f2-)
        local HNAMESUM_HTML=`echo ${rep_base}--${HNAME_FN}--${period}.html`
        local HNAMESUM_PDF=`echo ${rep_base}--${HNAME_FN}--${period}.pdf`

        # XXX hack
        # if this report has any data associated with this hostname,
        # it'll contain the ">100%<" char sequence (at least one copy)
        # (this test also implicitly checks that the html/pdf reports exists)
        # grep exit status: 0=match, 1=no match, 2=error (no file)
        grep ">100%<" ${tran_dir}/${HNAMESUM_HTML} > /dev/null 2>&1
        local gstat=$?
        if [ $gstat == 1 ]; then
            # no data
            rm -f ${tran_dir}/${HNAMESUM_HTML}
            rm -f ${tran_dir}/${HNAMESUM_PDF}
            continue
        elif [ $gstat == 2 ]; then
            # no file
            continue
        fi

        if [ "$generate_email_index" = true ]; then

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px;">$HNAME</span></td>
  <td colspan=6><span style="font-family: SansSerif; font-size: 9.0px; text-align: right">(<a href="$HNAMESUM_PDF">PDF</a>)&nbsp;</span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

        else

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=4><span style="font-family: SansSerif; font-size: 9.0px;">$HNAME</span></td>
  <td colspan=6><span style="font-family: SansSerif; font-size: 9.0px; text-align: right">(<a href="$HNAMESUM_HTML">HTML</a> | <a href="$HNAMESUM_PDF">PDF</a>)&nbsp;</span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

        fi

        hcnt=$((hcnt+1))

    done < $base_dir/hname.lst

    if (( hcnt == 0 )); then

cat >> $base_file <<EOF
<tr valign=top>
  <td><img src="../images/px" style="width: 20px; height: 13px"></td>
  <td colspan=12><span style="font-family: SansSerif; font-size: 9.0px;">
  &lt;No client events were detected during this time period.&gt;
  </span></td>
  <td colspan=9><img src="../images/px" style="width: 316px; height: 13px"></td>
</tr>
EOF

    fi
}

generate_page

cd $OLD_PWD
