#! /bin/sh

FILE=/etc/default/untangle-hw

echo "  Customizing HW-related settings for untangle-vm"

ARCH=`uname -m`
MEM=$(awk '/MemTotal/ { print $2 }' < /proc/meminfo)
if [ $MEM -gt 4900000 ] ; then
    MAX_HEAP_SIZE=`echo $MEM | awk '{printf $1 * .7 / 1000 "m"}'`
    MAX_VIRTUAL_SIZE=`echo $MEM | awk '{printf $1 * 1  / 1000 "m"}'`
    MAX_BERKDB_MEG=180
elif [ $MEM -gt 3900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=2200m
        MAX_VIRTUAL_SIZE=4400m
        MAX_BERKDB_MEG=180
    else
        MAX_HEAP_SIZE=2200m
        MAX_VIRTUAL_SIZE=4400m
        MAX_BERKDB_MEG=180
    fi
elif [ $MEM -gt 2900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=1500m
        MAX_VIRTUAL_SIZE=3000m
        MAX_BERKDB_MEG=120
    else
        MAX_HEAP_SIZE=1500m
        MAX_VIRTUAL_SIZE=3000m
        MAX_BERKDB_MEG=120
    fi
elif [ $MEM -gt 1900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=720m
        MAX_VIRTUAL_SIZE=1500m
        MAX_BERKDB_MEG=100
    else
        MAX_HEAP_SIZE=720m
        MAX_VIRTUAL_SIZE=1500m
        MAX_BERKDB_MEG=80
    fi
elif [ $MEM -gt 900000 ] ; then
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=360m
        MAX_VIRTUAL_SIZE=1000m
        MAX_BERKDB_MEG=48
    else
        MAX_HEAP_SIZE=360m
        MAX_VIRTUAL_SIZE=1000m
        MAX_BERKDB_MEG=32
    fi
else
    if [ $ARCH = 'x86_64' ]; then
        MAX_HEAP_SIZE=260m
        MAX_VIRTUAL_SIZE=1000m
        MAX_BERKDB_MEG=24
    else
        MAX_HEAP_SIZE=220m
        MAX_VIRTUAL_SIZE=1000m
        MAX_BERKDB_MEG=20
    fi
fi

MAX_VIRTUAL_SIZE=$(( ${MAX_VIRTUAL_SIZE/m} * 1000 ))

echo "    Maximum heap size -> ${MAX_HEAP_SIZE}"
echo "    Maximum BDB size -> ${MAX_BERKDB_MEG}M"
echo "    Maximum virtual size -> ${MAX_VIRTUAL_SIZE}"

cat >| $FILE <<EOF
MAX_HEAP_SIZE=$MAX_HEAP_SIZE
MAX_BERKDB_MEG=$MAX_BERKDB_MEG
MAX_VIRTUAL_SIZE=$MAX_VIRTUAL_SIZE
EOF
