#!/bin/sh

REGDONE="@MVVM_HOME@/.regdone"
REGINFO="@MVVM_HOME@/registration.info"

if [ -f "@MVVM_HOME@/activation.key" ]; then
    /usr/bin/update-reports &> /dev/null

    /usr/bin/find /tmp -mtime +31 -name "*.tmp" | /usr/bin/xargs /bin/rm
    /usr/bin/find @MVVM_HOME@/tmp -mtime +31 | /usr/bin/xargs /bin/rm

    if [ -f "$REGINFO" ]; then
        if [ ! -f "$REGDONE" -o "$REGDONE" -ot "$REGINFO" ]; then
            /usr/bin/mvregister
        fi
    fi
fi
