#! /bin/bash

main_index=@UVM_REPORTS@/current/$1
index=$1
period=$2
generate_email_index=$3
midnight=$4
mail_reports_arguments_daily=@PREFIX@/tmp/mail_reports_arguments_daily.txt
mail_reports_arguments_weekly=@PREFIX@/tmp/mail_reports_arguments_weekly.txt
mail_reports_arguments_monthly=@PREFIX@/tmp/mail_reports_arguments_monthly.txt

BRANDING_PROPS=@UVM_CONF@/branding.properties
COMPANY_NAME=$(grep '^uvm.branding.companyName=' $BRANDING_PROPS |sed 's/^[^=]\+=\(.*\)$/\1/')

## Parameters:
## <estat> : exit status
## <src> : source of error
function exitOnUvmError()
{
    local t_estat=$1
    local t_src=$2
    if [ $t_estat != 0 ]; then
        echo $t_src "error, exit status:" $t_estat
        exit $t_estat
    fi
}

if [ "$generate_email_index" != false ]; then
web_base=http://untangle.com/mail_blast
else
web_base=.
fi

cd @UVM_REPORTS@/current


ordered_tran_list=`@USR_BIN@/mcli instances | grep -i running | awk '{print $2}' | uniq | sed 's|^\(.*\)$|@UVM_REPORTS@/current/\1|'`
exitOnUvmError $? uvm


# generate email argument list
if [ "$generate_email_index" != false ]; then
    if [ "$period" = daily ]; then
    mail_reports_arguments="$mail_reports_arguments_daily"
    elif [ "$period" = weekly ]; then
    mail_reports_arguments="$mail_reports_arguments_weekly"
    elif [ "$period" = monthly ]; then
    mail_reports_arguments="$mail_reports_arguments_monthly"
    fi

    rm -f $mail_reports_arguments
    touch $mail_reports_arguments

    echo "--> mail_reports_arguments: $mail_reports_arguments"
fi


if [ "$generate_email_index" != false ]; then
    echo "-s \"$COMPANY_NAME Reports ($period)\"" >> $mail_reports_arguments
    echo "./$index" >> $mail_reports_arguments
    find ./images/* -type f >> $mail_reports_arguments
fi

generate_page ()
{
cat > $main_index <<EOF

<html xmlns="http://www.w3.org/1999/xhtml">

  <!-- HEADING -->
  <head>
    <title>$COMPANY_NAME Reports</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>


    <style type="text/css">
    <!--
body {
     margin: 15px;
     background: #FFFFFF url(images/background_body.gif) repeat-x top left;
     text-align: center;
}

table {
    font: normal normal normal 10pt/14pt Arial,Sans-Serif;
    text-align: left;
    color: #606060;
}

input {
    font: normal normal normal 10pt/14pt Arial,Sans-Serif;
    text-align: left;
    color: #606060;
}

form {
    margin: 0px;
}

a:link, a:visited {
    font: normal normal normal 10pt/14pt Arial,Sans-Serif;
    color: #1997FE;
    text-decoration: none;
}

a:hover {
    color: #1997FE;
    text-decoration: underline;
}

.page_header_title {
    font: bold normal normal 25pt Arial,Sans-Serif;
    color: #777777;
}

.page_header_alternate {
    font: normal normal normal 20pt Arial,Sans-Serif;
    color: #777777;
}

h1 {
    font: normal normal bold 11pt Arial,Sans-Serif;
    color: #999999;
    letter-spacing: 1px;
    margin: 0px;
    padding: 0px;
}

h2 {
    font: normal normal bold 10pt Arial,Sans-Serif;
    color: #999999;
    letter-spacing: 1px;
    margin: 0px;
    padding: 0px;
}

h3 {
    font: normal normal bold 11pt Arial,Sans-Serif;
    color: #606060;
    letter-spacing: 1px;
    margin: 0px;
    padding: 0px;
}

h4 {
    font: normal normal bold 14pt Arial,Sans-Serif;
    color: #0044D7;
    letter-spacing: 1px;
    margin: 0px;
    padding: 0px;
}

/* the following pertain to the main content (i.e. the main 'metal-brushed') table */
#table_main_center {
    background: url(images/background_table_main_center.gif) repeat-y;
}

#table_main_top {
    background: url(images/background_table_main_top.gif) repeat-x;
}

#table_main_top_left {
    background: url(images/rounded_corner_main_top_left.gif) no-repeat;
}

#table_main_top_right {
    background: url(images/rounded_corner_main_top_right.gif) no-repeat;
}

#table_main_right {
    background: url(images/background_table_main_right.gif) repeat-y;
}

#table_main_bottom {
    background: url(images/background_table_main_bottom.gif) repeat-x;
}

#table_main_bottom_left {
    background: url(images/rounded_corner_main_bottom_left.gif) no-repeat;
}

#table_main_bottom_right {
    background: url(images/rounded_corner_main_bottom_right.gif) no-repeat;
}

#table_main_left {
    background: url(images/background_table_main_left.gif) repeat-y;
}
    -->
   </style>
  </head>

  <!--BRUSHED METAL PAGE BACKGROUND -->
  <body>
    <center>
      <table border="0" cellpadding="0" cellspacing="0" width="904">

        <!-- TOP THIRD -->
        <tr>
          <td id="table_main_top_left">
            <img src="$web_base/images/spacer.gif" alt=" " width="23" height="23"/><br/>
          </td>
          <td width="100%" id="table_main_top">
            <img src="$web_base/images/spacer.gif" alt=" " width="1" height="1"/><br/>
          </td>
          <td id="table_main_top_right">
            <img src="$web_base/images/spacer.gif" alt=" " width="23" height="23"/><br/>
          </td>
        </tr>
        <!-- END TOP THIRD -->

        <!-- MIDDLE THIRD -->
        <tr>
          <td id="table_main_left">
            <img src="$web_base/images/spacer.gif" alt=" " width="1" height="1"/>
          </td>
          <td id="table_main_center">
            <table width="100%">
              <tr>
              <td width="96" valign="middle">
                <img src="/images/BrandingLogo.gif" alt="$COMPANY_NAME" width="150" height="96"/>
              </td>
              <td style="padding: 0px 0px 0px 10px" class="page_header_title" align="left" valign="middle">$COMPANY_NAME<br/>Reports</td>
              <td align="right">
              <table width="100%">
                <tr><td class="page_header_alternate" align="right">
EOF


if [ "$generate_email_index" = true ]; then
    if [ "$period" = daily ]; then
cat >> $main_index <<EOF
                <b>daily email</b><br/>
EOF
    elif [ "$period" = weekly ]; then
cat >> $main_index <<EOF
                <b>weekly email</b><br/>
EOF
    elif [ "$period" = monthly ]; then
cat >> $main_index <<EOF
                <b>monthly email</b><br/>
EOF
    fi
else
    if [ "$period" = daily ]; then
cat >> $main_index <<EOF
                <b>daily online</b><br/>
EOF
    elif [ "$period" = weekly ]; then
cat >> $main_index <<EOF
                <b>weekly online</b><br/>
EOF
    elif [ "$period" = monthly ]; then
cat >> $main_index <<EOF
                <b>monthly online</b><br/>
EOF
    fi
fi

echo
/bin/date -d''$midnight-1day'' +'%A %B %e, %Y' >> $main_index

cat >> $main_index <<EOF
    </td><tr>
    </table>
EOF

if [ "$generate_email_index" = false ]; then
cat >> $main_index <<EOF
    <a href="../archive">View Archived Reports</a>
EOF
fi

cat >> $main_index <<EOF
              </td>
              </tr>
            </table>
          </td>
          <td id="table_main_right">
            <img src="$web_base/images/spacer.gif" alt=" " width="1" height="1"/>
          </td>
        </tr>
        <!-- END MIDDLE THIRD -->
EOF

generate_content_area

cat >> $main_index <<EOF

        <!-- BOTTOM THIRD -->
        <tr>
          <td id="table_main_bottom_left">
            <img src="$web_base/images/spacer.gif" alt=" " width="23" height="23"/><br/>
          </td>
          <td id="table_main_bottom">
            <img src="$web_base/images/spacer.gif" alt=" " width="1" height="1"/><br/>
          </td>
          <td id="table_main_bottom_right">
            <img src="$web_base/images/spacer.gif" alt=" " width="23" height="23"/><br/>
          </td>
        </tr>
        <!-- END BOTTOM THIRD -->

      </table>
    </center>

  </body>
  <!-- END BRUSHED METAL PAGE BACKGROUND -->

</html>

EOF
}

generate_content_area ()
{
cat >> $main_index <<EOF
        <!-- CONTENT AREA -->
        <tr>
          <td id="table_main_left"></td>

          <!-- CENTER CELL -->
          <td id="table_main_center" style="padding: 15px 0px 0px 0px">
            <hr width="100%" size="1" color="#969696"/>
            <table width="100%" style="padding: 15px 0px 0px 0px">
              <tr>
EOF

    if [ $MV_EG_DAILY_REPORT == 'y' ] || [ $MV_EG_WEEKLY_REPORT == 'y' ] || [ $MV_EG_MONTHLY_REPORT == 'y' ]; then
    cat >> $main_index <<EOF
              <td width="200px" valign="top">
EOF

    generate_period_menu
        generate_report_menu
    generate_key

        cat >> $main_index <<EOF
              </td>
              <td align="right" valign="top">
EOF

    generate_summaries

    cat >> $main_index <<EOF
              </td>
EOF
   else
      cat >> $main_index <<EOF
    <center>
    <b><i>
        No reports are available.<br/>
        <br/>
        When daily, weekly, and/or monthly Reports are scheduled,<br/>
        please check back the morning after the scheduled day<br/>
        for daily, weekly, and/or monthly Reports.<br/>
        <br/>
        When scheduled, $COMPANY_NAME Reports automatically generates<br/>
        the requested Reports during the preceeding night.
        </i></b>
    </center>
EOF
   fi

    cat >> $main_index <<EOF
              </tr>
            </table>
            <hr width="100%" size="1" color="969696"/>
          </td>
          <!-- END CENTER CELL -->


          <td id="table_main_right"></td>
        </tr>
        <!-- END CONTENT AREA -->
EOF
}

generate_period_menu ()
{
if [ "$generate_email_index" = false ]; then
    cat >> $main_index <<EOF
                <table width="95%" border="1" bordercolor="bbbbbb" cellspacing="0" cellpadding="5">
                  <tr><td bgcolor="cccccc"><h3><b>Available Periods:</b></h3></td></tr>
EOF
    if [ $MV_EG_MONTHLY_REPORT == 'y' ]; then
        cat >> $main_index <<EOF
                  <tr><td> <a href="index_online_monthly.html">Monthly</a></td></tr>
EOF
    fi
    if [ $MV_EG_WEEKLY_REPORT == 'y' ]; then
        cat >> $main_index <<EOF
                  <tr><td> <a href="index_online_weekly.html">Weekly</a></td></tr>
EOF
    fi
    if [ $MV_EG_DAILY_REPORT == 'y' ]; then
        cat >> $main_index <<EOF
                  <tr><td> <a href="index.html">Daily</a></td></tr>
EOF
    fi
cat >> $main_index <<EOF
                </table>
<br/>
EOF
fi
}

generate_report_menu ()
{
cat >> $main_index <<EOF
                <!-- Full Single file Reports -->
                <table width="95%" border="1" bordercolor="bbbbbb" cellspacing="0" cellpadding="5">
                  <tr><td bgcolor="cccccc">
                    <h3><b>Complete Reports:</b></h3>
                  </td></tr>
                  <tr>
                    <td>
                     <img src="${web_base}/images/acrobat_icon_small.gif" alt="pdf" height="18" width="18" align="middle"/>
                     <a href="${period}_briefing.pdf">Briefing</a>
                    </td>
                  </tr>
                  <tr>
                    <td>
                     <img src="${web_base}/images/acrobat_icon_small.gif" alt="pdf" height="18" width="18" align="middle"/>
                      <a href="${period}_detailed.pdf">Detailed Report</a>
                    </td>
                  </tr>
                </table>
                </br>
EOF

cat >> $main_index <<EOF
                <!-- AVAILABLE REPORTS -->
                <table width="95%" border="1" bordercolor="bbbbbb" cellspacing="0" cellpadding="5">
                  <tr><td bgcolor="cccccc">
                    <h3><b>Available Reports:</b></h3>
                  </td></tr>
EOF

cat >> $main_index <<EOF
                  <tr><td>
                    &gt; <a href="#Platform">Platform</a>
                  </td></tr>
EOF

## This assumes that mcli never returns node names that contain spaces
for f in $ordered_tran_list; do
    if [ -d $f ]; then
        generate_report_menu_entry $f
    fi
done

cat >> $main_index <<EOF
                </table>
<br/>
                <!-- END AVAILABLE REPORTS -->
EOF

}

generate_key ()
{
cat >> $main_index <<EOF
<center>
<table border="0">
<tr><td><b>Key:</b><td></tr>
<tr><td>K = x 1,000<br/><td></tr>
<tr><td>M = x 1,000,000<br/><td></tr>
<tr><td>G = x 1,000,000,000<br/><td></tr>
</table>
</center>
EOF
}


generate_report_menu_entry ()
{
tran_dir=$1
ls $tran_dir/name >/dev/null 2>&1 || return
tran_name=$(cat $tran_dir/name)

if [ "$tran_name" = "Platform" ]; then
    return;
fi

cat >> $main_index <<EOF
                  <tr><td>
                    > <a href="#$tran_name">$tran_name</a>
                  </td></tr>
EOF
echo "generating menu entry: $tran_name"
}

generate_summaries ()
{
cat >> $main_index <<EOF
              <!-- SUMMARY AREA -->
EOF

## This assumes that mcli never returns node names that contain spaces
for f in $ordered_tran_list; do
    if [ -d $f ]; then
        generate_summary_entry $f false
    fi
done


## This assumes that mcli never returns node names that contain spaces
for f in $ordered_tran_list; do
    if [ -d $f ]; then
        generate_summary_entry $f true
    fi
done

cat >> $main_index <<EOF
              <!-- END SUMMARY AREA -->
EOF
}

generate_summary_entry ()
{
# true allows you to print only non Platform software, false
# allows you to print only Platform software
tran_dir=$1
ls $tran_dir/name >/dev/null 2>&1 || return
tran_name=$(cat $tran_dir/name)

if [ "$2" = false ]; then
    if [ "$tran_name" != "Platform" ]; then
    return
    fi
else
    if [ "$tran_name" = "Platform" ]; then
    return
    fi
fi


rel_dir=$(echo $1 | sed -e 's/^\(.*\/current\/\)//')
#rel_dir=$(echo $1 | sed -e 's/^\(.*\/current\)/./')


# generate email argument list
if [ "$generate_email_index" = true ]; then
    if [ "$period" = daily ]; then
    find $rel_dir/*daily.pdf -type f >> $mail_reports_arguments
    elif [ "$period" = weekly ]; then
    find $rel_dir/*weekly.pdf -type f >> $mail_reports_arguments
    elif [ "$period" = monthly ]; then
    find $rel_dir/*monthly.pdf -type f >> $mail_reports_arguments
    fi
fi

cat >> $main_index <<EOF
              <a name="$tran_name"/>
              <table width="95%" border="1" bordercolor="bbbbbb" cellspacing="0" cellpadding="5">
                <tr><td colspan="2" bgcolor="cccccc">
                  <table>
                  <tr>
EOF

cat >> $main_index <<EOF
                  <td style="padding: 0px 4px 0px 0px"><img src="$web_base/$rel_dir/images/IconDesc42x42.png" width="42" height="42"/></td>
EOF


cat >> $main_index <<EOF
                  <td><h3><b>$tran_name Report</b></h3></td>
                  </tr>
                  </table>
                </td></tr>
EOF


if [ -f $1/*Summary_Graph--${period}.png ]; then
cat >> $main_index <<EOF
                <tr>
                  <td>
                     <b>Visual Summary:</b><br/>
EOF

generate_visual_summary $1

cat >> $main_index <<EOF
                  </td>
                </tr>
EOF
fi


cat >> $main_index <<EOF
                <tr>
                  <td>
                    <b>Vital Statistics:</b><br/>
EOF

generate_vital_statistics $1

cat >> $main_index <<EOF
                  </td>
                </tr>
                <tr>
                  <td colspan="2">
                    <b>Detailed Reports:</b><br/>
EOF

generate_detailed_reports $1

cat >> $main_index <<EOF
                  </td>
                </tr>
              </table>
<br/><br/>
EOF
echo "generating summary index : $tran_name : $2"
}

generate_vital_statistics ()
{
cat >>$main_index <<EOF
<!-- VITAL STATISTICS -->
<table width="100%" style="padding: 0px 0px 0px 15px" cellspacing="0">
EOF

    #tran_dir=$1
    #tran_name=$(cat $tran_dir/name)
    rel_dir=$(echo $1 | sed -e 's/^\(.*\/current\/\)//')


    if [ "$period" = daily ]; then
    cat $rel_dir/sum-daily.html | cat >> $main_index
    elif [ "$period" = weekly ]; then
    cat $rel_dir/sum-weekly.html | cat >> $main_index
    elif [ "$period" = monthly ]; then
    cat $rel_dir/sum-monthly.html | cat >> $main_index
    fi

cat >>$main_index <<EOF
</table>
<!-- END VITAL STATISTICS -->
EOF
}


generate_visual_summary ()
{
    rel_dir=$(echo $1 | sed -e 's/^\(.*\/current\/\)//')
    cat $tran_dir/report-files | while read line; do
        base_name=$(echo $line | cut -d: -f2)
        graph_name=$(echo $line | cut -d: -f3-)
        if [ xsummaryGraph = "x$base_name" ] ; then
cat >>$main_index <<EOF
<!-- VISUAL SUMMARY -->
<center>
<img src="$rel_dir/$graph_name--${period}.png" width="600" height="200" alt="Visual Summary may take some additional time to load.  If it does not load, it may not viewable from this email client.  Please use your browser to view reports directly from the Platform."/>
</center>
<!-- END VISUAL SUMMARY -->
EOF

            if [ "$generate_email_index" = true ]; then
                echo "$rel_dir/$graph_name--${period}.png" >> $mail_reports_arguments
            fi
        fi
    done
}


generate_detailed_reports ()
{
    #tran_dir=$1
    #tran_name=$(cat $tran_dir/name)
    rel_dir=$(echo $1 | sed -e 's/^\(.*\/current\/\)//')

cat >>$main_index <<EOF
<!-- DETAILED REPORTS -->
<table width="100%" style="padding: 0px 0px 0px 15px" cellspacing="0">
<tr>
EOF

    if [ "$period" = daily ]; then
cat >>$main_index <<EOF
<td width="*" align="right" colspan="4"><i>daily&nbsp;</i></td>
EOF
    fi
    if [ "$period" = weekly ]; then
cat >>$main_index <<EOF
<td width="*" align="right" colspan="4"><i>weekly&nbsp;</i></td>
EOF
    fi
    if [ "$period" = monthly ]; then
cat >>$main_index <<EOF
<td width="*" align="right" colspan="4"><i>monthly&nbsp;</i></td>
EOF
    fi

cat >>$main_index <<EOF
</tr>
EOF

alternate=0

cat $tran_dir/report-files | while read line; do
    base_name=$(echo $line | cut -d: -f2)
    rep_name=$(echo $line | cut -d: -f3-)
    if [ xscanner != "x$base_name" ] && [ xsummarizer != "x$base_name" ] && [ xsummaryGraph != "x$base_name" ] && [ xparameter != "x$base_name" ] ; then
        if (( alternate % 2 )); then
            color="dddddd"
    else
            color="eeeeee"
        fi

if [ xuserSummary = "x$base_name" ] ; then
    generate_user_summary $rel_dir $rep_name
    display_name="User Summary"
    base_tmp=$rep_name
elif [ xhNameSummary = "x$base_name" ] ; then
# the data for this page is handled with userSummary
    continue
else
    display_name=$rep_name
    base_tmp=$base_name
fi

cat >>$main_index <<EOF
<tr bgcolor=$color>
<td width="*">&nbsp;$display_name: </td>
EOF

if [ "$generate_email_index" = true ]; then
    if [ "$period" = daily ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--daily.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
    if [ "$period" = weekly ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--weekly.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
    if [ "$period" = monthly ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--monthly.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
else
    if [ "$period" = daily ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--daily.html">HTML</a> | <a href="$rel_dir/$base_tmp--daily.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
    if [ "$period" = weekly ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--weekly.html">HTML</a> | <a href="$rel_dir/$base_tmp--weekly.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
    if [ "$period" = monthly ]; then
cat >> $main_index <<EOF
<td width="375px" align="right" colspan="3">(<a href="$rel_dir/$base_tmp--monthly.html">HTML</a> | <a href="$rel_dir/$base_tmp--monthly.pdf">PDF</a>)&nbsp;</td>
EOF
    fi
fi

alternate=$((alternate+1))
    fi
done

cat >>$main_index <<EOF
</table>
<!-- END DETAILED REPORTS -->
EOF

}

generate_user_summary ()
{
tran_dir=$1
rep_base=$2
# generate the web viewable page
    if [ $MV_EG_DAILY_REPORT == 'y' ]; then
        @UVM_HOME@/reports/usersummary-reports $tran_dir $rep_base daily $generate_email_index
    fi
    if [ $MV_EG_WEEKLY_REPORT == 'y' ]; then
        @UVM_HOME@/reports/usersummary-reports $tran_dir $rep_base weekly $generate_email_index
    fi
    if [ $MV_EG_MONTHLY_REPORT == 'y' ]; then
        @UVM_HOME@/reports/usersummary-reports $tran_dir $rep_base monthly $generate_email_index
    fi
}

generate_page
