#! /bin/bash

set -e

JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-1.5.0-sun}

# We need the whole UVM since we can't boot hibernate without
# it. Also MVPatternLayout is in bootstrap.jar.
CLASSPATH="@UVM_LIB@/untangle-vm-bootstrap/:@UVM_LIB@/untangle-vm-impl/:@UVM_LIB@/untangle-vm-api/:@UVM_LIB@/untangle-vm-localapi/:@UVM_HOME@/conf"
for f in @THIRDPARTY_UVM_LIB@/*jar ; do
    CLASSPATH="$CLASSPATH:$f"
done
export CLASSPATH

$JAVA_HOME/bin/java \
    -Dlog4j.configuration=file:@UVM_HOME@/conf/log4j-reporter.xml \
    -Dbunnicula.home=@UVM_HOME@ \
    com.untangle.uvm.engine.MailSenderImpl @UVM_LIB@/untangle-vm-impl/ "$@"
