#! /bin/bash

set -e

source @PREFIX@/etc/default/untangle-vm

# We need the whole UVM since we can't boot hibernate without
# it. Also MVPatternLayout is in bootstrap.jar.
CLASSPATH="@UVM_LIB@/untangle-libuvm-bootstrap/:@UVM_LIB@/untangle-libuvm-impl/:@UVM_LIB@/untangle-libuvm-api/:@UVM_LIB@/untangle-libuvm-localapi/:@UVM_HOME@/conf"
for f in @THIRDPARTY_UVM_LIB@/*jar ; do
    CLASSPATH="$CLASSPATH:$f"
done
export CLASSPATH

$JAVA_HOME/bin/java \
    -Dlog4j.configuration=file:@UVM_HOME@/conf/log4j-reporter.xml \
    -Dbunnicula.home=@UVM_HOME@ \
    com.untangle.uvm.engine.MailSenderImpl @UVM_LIB@/untangle-libuvm-impl/ "$@"
