#! /bin/bash

set -e

source @PREFIX@/etc/default/untangle-vm

CLASSPATH="@UVM_LIB@/uvm/"
for f in @THIRDPARTY_REPORTS_LIB@/*jar ; do
    CLASSPATH="$CLASSPATH:$f"
done
# for m in @UVM_TOOLBOX@/*.mar; do CLASSPATH="$CLASSPATH:$m"; done
export CLASSPATH

exec ${JAVA_HOME}/bin/java com.untangle.node.reporting.summary.SummaryApp $@
