#!/bin/dash

# Start of script
mkdir -p /var/log/untangle-cpd
exec >> /var/log/untangle-cpd/monitor.log 2>&1

set -e

file_name=$1

if [ ! -f "${file_name}" ]; then
    logger -t untangle-node-cpd "The file '${file_name}' doesn't exist."
    exit 1
fi


logger -t untangle-node-cpd "Removing the old custom directory"
rm -rf "@UVM_WEB@/cpd/custom"

logger -t untangle-node-cpd "Unzipping the file '$file_name'."

## Expand the files into UVM_WEB/cpd
unzip "${file_name}" "custom/*" -d "@UVM_WEB@/cpd"
