#!/bin/dash

set -e

mkdir -p /var/log/untangle-cpd
exec >> /var/log/untangle-cpd/monitor.log 2>&1

CPD_BIND_PORT=3005

/etc/init.d/untangle-cpd restart

logger -t untangle-node-cpd "Started cpd."

is_running()
{
    curl -sf -F 'json_request=@-' -m 2 "http://localhost:${CPD_BIND_PORT}"  > /dev/null 2>&1 <<EOF
{ "function" : "hello_world" }
EOF
}

started=false
for t in `seq 1 10`; do
    sleep 0.5

    is_running && {
        started=true
        break;
    }
done

if [ "$started" != "true" ]; then
    logger -t untangle-node-cpd "Unable to start the captive Portal Daemon."
    exit 1
fi

logger -t untangle-node-cpd "Waited ${t} ticks for cpd to start."

RELOAD_APACHE=false

# Create a symlink for apache to know where the captive portal redirects are.
if [ ! -h /etc/apache2/sites-enabled/cpd.conf ]; then
    ln -sf @UVM_HOME@/cpd/apache2-cpd.conf /etc/apache2/sites-enabled/cpd.conf
    RELOAD_APACHE=true
fi

# Enable apache rewrite
if [ ! -h /etc/apache2/mods-enabled/rewrite.load ]; then
    ln -sf /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
    RELOAD_APACHE=true
fi

if [ "${RELOAD_APACHE}" = "true" ]; then
    logger -t untangle-node-cpd "Reloading apache"
    

    # Reload apache
    /etc/init.d/apache2 reload
    
    logger -t untangle-node-cpd "Reload Apache complete"
fi

