
/*
 * Copyright (c) 2003,2004 Metavize Inc.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Metavize Inc. ("Confidential Information").  You shall
 * not disclose such Confidential Information.
 *
 */
package com.metavize.tran.protofilter;

import java.util.LinkedHashMap;

/**
 * WARNING WARNING WARNING WARNING WARNING WARNING
 *
 * This class is autogenerated, do not edit
 *
 * WARNING WARNING WARNING WARNING WARNING WARNING
 */

public class LoadPatterns {

    private static LinkedHashMap patterns = null;
    
    private LoadPatterns() {}

    public static synchronized LinkedHashMap getPatterns()
    {
        if (patterns == null)
            patterns = createPatterns();
        return patterns;
    }

    private static LinkedHashMap createPatterns()
    {
        LinkedHashMap pats = new LinkedHashMap();


		pats.put("AIM",new ProtoFilterPattern("AIM","Instant Messenger"," AOL instant messenger (OSCAR and TOC)","^(\\*[\\x01\\x02].*\\x03\\x0b|\\*\\x01.?.?.?.?\\x01)|flapon|toc_signon.*0x","good",false,false,false));
		pats.put("AIM web content",new ProtoFilterPattern("AIM web content","Instant Messenger"," ads/news content downloaded by AOL Instant Messenger","user-agent:aim/","good",false,false,false));
		pats.put("Apple Juice",new ProtoFilterPattern("Apple Juice","Peer to Peer"," P2P filesharing - http://www.applejuicenet.de/","ajprot\\x0d\\x0a","ok",false,false,false));
		pats.put("Audiogalaxy",new ProtoFilterPattern("Audiogalaxy","Music"," Peer to Peer filesharing","^(\\x45\\x5f\\xd0\\xd5|\\x45\\x5f.*0.60(6|8)W)","ok",false,false,false));
		pats.put("Battlefield 1942",new ProtoFilterPattern("Battlefield 1942","Video Game"," An EA game","^\\x01\\x11\\x10\\x7c\\xf8\\x02\\x10\\x40\\x06","ok",false,false,false));
		pats.put("BGP",new ProtoFilterPattern("BGP","Networking"," Border Gateway Protocol - RFC 1771","^\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff..?\\x01[\\x03\\x04]","ok",false,false,false));
		pats.put("Biff",new ProtoFilterPattern("Biff","Email"," new mail notification","^[a-z][a-z0-9]+@[1-9][0-9]+$","good",false,false,false));
		pats.put("Bittorrent",new ProtoFilterPattern("Bittorrent","Peer to Peer"," http://sourceforge.net/projects/bittorrent/","^\\x13bittorrent protocol","great",false,false,false));
		pats.put("Cisco VPN",new ProtoFilterPattern("Cisco VPN","Networking"," VPN client software to a Cisco VPN server","^\\x01\\xf4\\x01\\xf4","ok",false,false,false));
		pats.put("Code Red",new ProtoFilterPattern("Code Red","Worm"," a worm that attacks Microsoft IIS web servers","/default\\.ida\\?NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN%u9090%u6858%ucbd3%u7801%u9090%u6858%ucbd3%u7801%u9090%u6858%ucbd3%u7801%u9090%u9090%u8190%u00c3%u0003%u8b00%u531b%u53ff%u0078%u0000%u00=a","ok",false,false,false));
		pats.put("Counter Strike",new ProtoFilterPattern("Counter Strike","Video Game"," A popular computer game.","cs .*dl.www.counter-strike.net","ok",false,false,false));
		pats.put("CVS",new ProtoFilterPattern("CVS","Software Development"," Concurrent Versions System","^BEGIN (AUTH|VERIFICATION|GSSAPI) REQUEST\\x0a","good",false,false,false));
		pats.put("DHCP",new ProtoFilterPattern("DHCP","Networking"," Dynamic Host Configuration Protocol (RFC 1541)","^(\\x01|\\x02)[\\x01- ]\\x06.*c\\x82sc","good",false,false,false));
		pats.put("Direct Connect",new ProtoFilterPattern("Direct Connect","Peer to Peer"," Peer to Peer filesharing http://www.neo-modus.com/","^(\\$mynick |\\$lock |\\$key )","good",false,false,false));
		pats.put("DNS",new ProtoFilterPattern("DNS","Networking"," Domain Name System (RFC 1035)","^.?.?.?.?[\\x01\\x02].?.?.?.?.?.?[\\x01-\\x3F][a-z][\\x01-\\x3Fa-z]*[\\x02-\\x06][a-z][a-z][fglmoprstuvz]?[aeop]?(um)?[\\x01-\\x10][\\x01\\x03\\x04\\xFF]","good",false,false,false));
		pats.put("FastTrack",new ProtoFilterPattern("FastTrack","Peer to Peer"," Peer to Peer filesharing (Kazaa, Morpheus, iMesh, Grokster, etc)","^get (/.download/[ -~]*|/.supernode[ -~]|/.status[ -~]|/.network[ -~]*|/.files|/.hash=[0-9a-f]*/[ -~]*) http/1.1|user-agent: kazaa|x-kazaa(-username|-network|-ip|-supernodeip|-xferid|-xferuid|tag)|^give [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]?[0-9]?[0-9]?","good",false,false,false));
		pats.put("FTP",new ProtoFilterPattern("FTP","File Transfer"," File Transfer Protocol (RFC 959)","^220[\\x09-\\x0d -~]*ftp","great",false,false,false));
		pats.put("Gkrellm",new ProtoFilterPattern("Gkrellm","System Administration"," a system monitor (http://gkrellm.net)","^<gkrellmd_setup>","good",false,false,false));
		pats.put("GnucleusLAN (the LAN-only version)",new ProtoFilterPattern("GnucleusLAN (the LAN-only version)","Peer to Peer","only version) - Peer-to-peer file sharing","gnuclear connect/[\\x09-\\x0d -~]*user-agent: gnucleus [\\x09-\\x0d -~]*lan:","good",false,false,false));
		pats.put("Gnutella",new ProtoFilterPattern("Gnutella","Peer to Peer"," Peer-to-peer file sharing","^gnd[\\x01\\x02]?.?.?\\x01|^(gnutella connect/[012]\\.[0-9]\\x0d\\x0a[\\x09-\\x0d -~]*\\x0d\\x0ax-ultrapeer:|gnutella connect/[012]\\.[0-9] 200 ok\\x0d\\x0a[\\x09-\\x0d -~]*\\x0d\\x0ax-ultrapeer:|get /uri-res/n2r\\?urn:sha1:|get /[\\x09-\\x0d -~]*(gwebcache|gcache|gwc)|get /[\\x09-\\x0d -~]*user-agent: (gtk-gnutella|bearshare|mactella|gnucleus|gnotella|limewire|imesh|winmx)|get /[\\x09-\\x0d -~]*content-type: application/x-gnutella-packets|giv [0-9]*:[0-9a-f]*/|queue [0-9a-f]* [1-9][0-9]?[0-9]?\\.[1-9][0-9]?[0-9]?\\.[1-9][0-9]?[0-9]?\\.[1-9][0-9]?[0-9]?:[1-9][0-9]?[0-9]?[0-9]?)","good",false,false,false));
		pats.put("GoBoogy",new ProtoFilterPattern("GoBoogy","Peer to Peer"," A Japanese (?) P2P protocol","<peerplat>|^get /getfilebyhash\\.cgi\\?|^get /queue_register\\.cgi\\?|^get /getupdowninfo\\.cgi\\?","marginal",false,false,false));
		pats.put("H.323",new ProtoFilterPattern("H.323","Voice over IP"," Voice over IP.","^\\x03..?\\x08...?.?.?.?.?.?.?.?.?.?.?.?.?.?.?\\x05","ok",false,false,false));
		pats.put("hddtemp",new ProtoFilterPattern("hddtemp","System Administration"," Hard drive temperature reporting","^\\|/dev/[a-z][a-z][a-z]\\|[0-9a-z]*\\|[0-9][0-9]\\|[cfk]\\|","great",false,false,false));
		pats.put("Hotline",new ProtoFilterPattern("Hotline","Peer to Peer"," An old P2P protocol","^....................TRTPHOTL\\x01\\x02","marginal",false,false,false));
		pats.put("HTTP",new ProtoFilterPattern("HTTP","Web"," HyperText Transfer Protocol (RFC 2616)","http/(0\\.9|1\\.0|1\\.1) [1-5][0-9][0-9] [\\x09-\\x0d -~]*(connection:|content-type:|content-length:)|post [\\x09-\\x0d -~]* http/[01]\\.[019]","great",false,false,false));
		pats.put("Ident",new ProtoFilterPattern("Ident","Networking"," Identification Protocol - RFC 1413","^[1-9][0-9]?[0-9]?[0-9]?[0-9]?[\\x09-\\x0d]*,[\\x09-\\x0d]*[1-9][0-9]?[0-9]?[0-9]?[0-9]?(\\x0d\\x0a|[\\x0d\\x0a])?$","good",false,false,false));
		pats.put("IMAP",new ProtoFilterPattern("IMAP","Email"," Internet Message Access Protocol (A common e-mail protocol)","^(\\* ok|a[0-9]+ noop)","good",false,false,false));
		pats.put("IP printing",new ProtoFilterPattern("IP printing","Printing"," a new standard for UNIX printing - RFC 2911","ipp://","good",false,false,false));
		pats.put("IRC",new ProtoFilterPattern("IRC","Instant Messenger"," Internet Relay Chat - RFC 1459","^nick[\\x09-\\x0d -~]*user[\\x09-\\x0d -~]*:|^user[\\x09-\\x0d -~]*:[\\x09-\\x0d -~]*nick[\\x09-\\x0d -~]*\\x0d\\x0a","good",false,false,false));
		pats.put("Jabber (XMPP)",new ProtoFilterPattern("Jabber (XMPP)","Instant Messenger"," an open instant messenger protocol - http://jabber.org","<stream:stream[\\x09-\\x0d ][ -~]*[\\x09-\\x0d ]xmlns=['\"]jabber","good",false,false,false));
		pats.put("live365",new ProtoFilterPattern("live365","Music"," An Internet radio site (http://live365.com)","membername.*session.*player","marginal",false,false,false));
		pats.put("LPD",new ProtoFilterPattern("LPD","Printing"," Line Printer Daemon Protocol - RFC 1179 - old-style UNIX printing","^(\\x01[!-~]+|\\x02[!-~]+\\x0a.[\\x01\\x02\\x03][\\x01-\\x0a -~]*|[\\x03\\x04][!-~]+[\\x09-\\x0d]+[a-z][\\x09-\\x0d -~]*|\\x05[!-~]+[\\x09-\\x0d]+([a-z][!-~]*[\\x09-\\x0d]+[1-9][0-9]?[0-9]?|root[\\x09-\\x0d]+[!-~]+).*)\\x0a$","ok",false,false,false));
		pats.put("MSN Filetransfers",new ProtoFilterPattern("MSN Filetransfers","Instant Messenger"," Filetransfers as used by MSN Messenger","^ver [ -~]*msnftp\\x0d\\x0aver msnftp\\x0d\\x0ausr","good",false,false,false));
		pats.put("MSN Messenger",new ProtoFilterPattern("MSN Messenger","Instant Messenger"," Microsoft Network chat client","^(ver [0-9]+ msnp[1-9][0-9]? [\\x09-\\x0d -~]* cvr|usr md5 i [ -~]*)","good",false,false,false));
		pats.put("MUTE",new ProtoFilterPattern("MUTE","Peer to Peer"," Peer to Peer filesharing - http://mute-net.sourceforge.net/","^(Public|AES)Key: [0-9a-f]*\\x0aEnd(Public|AES)Key\\x0a$","marginal",false,false,false));
		pats.put("Netbios name service",new ProtoFilterPattern("Netbios name service","Networking","Netbios name service","\\x01\\x10\\x01|\\)\\x10\\x01\\x01|0\\x10\\x01","good",false,false,false));
		pats.put("NCP",new ProtoFilterPattern("NCP","Networking"," Novell Core Protocol","^(dmdt.*\\x01.*(\"\"|\\x11\\x11|uu)|tncp.*33)","good",false,false,false));
		pats.put("Nimda",new ProtoFilterPattern("Nimda","Worm"," a worm that attacks Microsoft IIS web servers, and MORE!","GET (/scripts/root\\.exe\\?/c\\+dir|/MSADC/root\\.exe\\?/c\\+dir|/c/winnt/system32/cmd\\.exe\\?/c\\+dir|/d/winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.%5c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/_vti_bin/\\.\\.%5c\\.\\./\\.\\.%5c\\.\\./\\.\\.%5c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/_mem_bin/\\.\\.%5c\\.\\./\\.\\.%5c\\.\\./\\.\\.%5c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/msadc/\\.\\.%5c\\.\\./\\.\\.%5c\\.\\./\\.\\.%5c/\\.\\.\\xc1\\x1c\\.\\./\\.\\.\\xc1\\x1c\\.\\./\\.\\.\\xc1\\x1c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.\\xc1\\x1c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.\\xc0/\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.\\xc0\\xaf\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.\\xc1\\x9c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.%35c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.%35c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.%5c\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir|/scripts/\\.\\.%2f\\.\\./winnt/system32/cmd\\.exe\\?/c\\+dir)","ok",false,false,false));
		pats.put("NNTP",new ProtoFilterPattern("NNTP","Internet News"," Network News Transfer Protocol (RFC 977, 2980)","^(20[01][\\x09-\\x0d -~]*AUTHINFO USER|20[01][\\x09-\\x0d -~]*news)","good",false,false,false));
		pats.put("OpenFT : P2P network (implemented in giFT library)",new ProtoFilterPattern("OpenFT : P2P network (implemented in giFT library)","Peer to Peer","OpenFT : P2P network (implemented in giFT library)","x-openftalias: [-)(0-9a-z ~.]","ok",false,false,false));
		pats.put("POP3",new ProtoFilterPattern("POP3","Email"," Post Office Protocol version 3 (popular e-mail protocol) - RFC 1939","^(\\+ok |-err )","good",false,false,false));
		pats.put("pressplay",new ProtoFilterPattern("pressplay","Music"," A legal music distribution site (http://pressplay.com)","user-agent: nsplayer","ok",false,false,false));
		pats.put("Quake 1",new ProtoFilterPattern("Quake 1","Video Game"," A popular computer game.","^\\x80\\x0c\\x01quake\\x03","marginal",false,false,false));
		pats.put("Quake 2, Quake 3, Quake World, Half Life",new ProtoFilterPattern("Quake 2, Quake 3, Quake World, Half Life","Video Game"," popular computer games.","^\\xff\\xff\\xff\\xffget(info|challenge)","good",false,false,false));
		pats.put("RDP",new ProtoFilterPattern("RDP","Remote Deskop"," Remote Desktop Protocol (used in Windows Terminal Services)","rdpdr.*cliprdr.*rdpsnd","ok",false,false,false));
		pats.put("rlogin",new ProtoFilterPattern("rlogin","System Administration"," remote login (RFC 1282)","^[a-z][a-z0-9][a-z0-9]+/[1-9][0-9]?[0-9]?[0-9]?00","ok",false,false,false));
		pats.put("RTSP",new ProtoFilterPattern("RTSP","Networking"," Real Time Streaming Protocol - http://www.rtsp.org/","rtsp/1.0 200 ok","good",false,false,false));
		pats.put("Shoutcast & Icecast",new ProtoFilterPattern("Shoutcast & Icecast","Music"," streaming audio","icy [1-5][0-9][0-9] [\\x09-\\x0d -~]*(content-type:audio|icy-)","good",false,false,false));
		pats.put("Skype",new ProtoFilterPattern("Skype","Instant Messenger"," UDP voice call (http://skype.com/)","^..\\x0d\\x6b..\\x0d\\x6b..\\x0d\\x6b$|..\\x0d\\x01..\\x0d\\x01$","marginal",false,false,false));
		pats.put("Samba/SMB",new ProtoFilterPattern("Samba/SMB","Networking"," Server Message Block - Microsoft File Sharing","\\xffsmb[\\x72\\x25]","good",false,false,false));
		pats.put("SMTP",new ProtoFilterPattern("SMTP","Email"," Simple Mail Transfer Protocol (RFC 2821) (See also RFC 1869)","^220[\\x09-\\x0d -~]* (e?smtp|simple mail)","good",false,false,false));
		pats.put("SNMP",new ProtoFilterPattern("SNMP","Networking"," Simple Network Management Protocol (RFC1157)","^\\x02\\x01\\x04.+([\\xa0-\\xa3]\\x02[\\x01-\\x04].?.?.?.?\\x02\\x01.?\\x02\\x01.?\\x30|\\xa4\\x06.+\\x40\\x04.?.?.?.?\\x02\\x01.?\\x02\\x01.?\\x43)","good",false,false,false));
		pats.put("SOCKS Version 5",new ProtoFilterPattern("SOCKS Version 5","Networking"," Firewall traversal protocol (RFC 1928)","\\x05[\\x01-\\x08]*\\x05[\\x01-\\x08]?.*\\x05[\\x01-\\x03][\\x01\\x03].*\\x05[\\x01-\\x08]?[\\x01\\x03]","marginal",false,false,false));
		pats.put("SSDP (Simple Service Discovery Protocol): helps computers find network devices",new ProtoFilterPattern("SSDP (Simple Service Discovery Protocol): helps computers find network devices","Networking","SSDP (Simple Service Discovery Protocol): helps computers find network devices","^notify[\\x09-\\x0d ]\\*[\\x09-\\x0d ]http/1\\.1[\\x09-\\x0d -~]*ssdp:(alive|byebye)|^m-search[\\x09-\\x0d ]\\*[\\x09-\\x0d ]http/1\\.1[\\x09-\\x0d -~]*ssdp:discover","good",false,false,false));
		pats.put("SSH",new ProtoFilterPattern("SSH","System Administration"," Secure SHell","^ssh-[12]\\.[0-9]","great",false,false,false));
		pats.put("Subspace",new ProtoFilterPattern("Subspace","Video Game"," 2D asteroids-style multiplayer space game (http://subspacehq.com)","^\\x01....\\x11\\x10........\\x01$","marginal",false,false,false));
		pats.put("Telnet",new ProtoFilterPattern("Telnet","System Administration"," Insecure remote login (RFC 854)","^\\xff[\\xfb-\\xfe].\\xff[\\xfb-\\xfe].\\xff[\\xfb-\\xfe]","good",false,false,false));
		pats.put("Tesla Advanced Communication",new ProtoFilterPattern("Tesla Advanced Communication","Peer to Peer"," P2P file sharing (?)","\\x03\\x9a\\x89\\x22\\x31\\x31\\x31\\x2e\\x30\\x30\\x20\\x42\\x65\\x74\\x61\\x20|\\xe2\\x3c\\x69\\x1e\\x1c\\xe9","marginal",false,false,false));
		pats.put("TFTP",new ProtoFilterPattern("TFTP","File Transfer"," Trivial File Transfer Protocol - used for bootstrapping (RFC 1350)","^(\\x01|\\x02)[ -~]*(netascii|octet|mail)","marginal",false,false,false));
		pats.put("TLS",new ProtoFilterPattern("TLS","Networking"," Transport Layer Security - RFC 2246","^\\x16\\x03\\x01.?.?\\x01.?.?.?\\x03\\x01","good",false,false,false));
		pats.put("TSP",new ProtoFilterPattern("TSP","Time"," Time Synchronization Protocol","^[\\x01-\\x13\\x16-\\x24]\\x01.?.?.?.?.?.?.?.?.?.?[ -~]+","good",false,false,false));
		pats.put("Valid certificate SSL",new ProtoFilterPattern("Valid certificate SSL","Networking"," Anything tunneled through SSL (i.e. HTTPS, IMAPS)","server-certs@thawte\\.com|equifax secure certificate authority|rsa data security, inc|verisign, inc|gte cybertrust root|entrust\\.net limited","good",false,false,false));
		pats.put("VNC",new ProtoFilterPattern("VNC","Remote Desktop"," Virtual Network Computing. Also known as RFB - Remote Frame Buffer","^rfb 00[1-9]\\.00[0-9]\\x0a$","good",false,false,false));
		pats.put("X Windows Version 11",new ProtoFilterPattern("X Windows Version 11","Remote Desktop"," Networked GUI system used in most Unices","^[lb].?\\x0b","good",false,false,false));
		pats.put("XBoxLive",new ProtoFilterPattern("XBoxLive","Video Game"," Console gaming","^\\x58\\x80........\\xf3|^\\x06\\x58\\x4e","marginal",false,false,false));
		pats.put("Yahoo messenger",new ProtoFilterPattern("Yahoo messenger","Instant Messenger"," an instant messenger protocol (http://yahoo.com)","^(ymsg|ypns|yhoo).?.?.?.?.?.?.?[lwt].*\\xc0\\x80","good",false,false,false));
		pats.put("ZMAAP",new ProtoFilterPattern("ZMAAP","Networking"," Zeroconf Multicast Address Allocation Protocol","^\\x1b\\xd7\\x3b\\x48[\\x01\\x02]\\x01?\\x01","ok",false,false,false));
		return pats;
	}
}
