#!/bin/dash

## Restart ipsec if already running
restart_ipsec()
{
    local t_pid
    t_pid=`cat /var/run/pluto/pluto.pid`
    grep -q pluto /proc/${t_pid}/cmdline && {
        echo "[`date`] Restarting ipsec"
        /etc/init.d/xl2tpd stop
        /etc/init.d/ipsec stop
        /etc/init.d/ipsec start
        /etc/init.d/xl2tpd start
        /usr/share/untangle/bin/ipsec-create-statfile
        break
    }
}

restart_ipsec 2> /dev/null

exit 0
