#! /bin/dash

### BEGIN INIT INFO
# Provides:          untangle-pyconnector
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

. /lib/lsb/init-functions

DESC="Untangle PyConnector"
DAEMON_NAME="ut-pyconnector"
BIN_NAME="/usr/share/untangle/bin/ut-pyconnector"
PID_FILE="/var/run/ut-pyconnector.pid"
LOG_FILE="/var/log/uvm/pyconnector.log"
OPTIONS="-l ${LOG_FILE}"

if [ -f /etc/default/pyconnector ] ; then
    . /etc/default/pyconnector
fi

start()
{
    log_daemon_msg "Starting $DESC"

    if [ -f ${PID_FILE} ] ; then
      ps -p `cat ${PID_FILE}` > /dev/null 2>&1 && grep $DAEMON_NAME /proc/`cat ${PID_FILE}`/cmdline > /dev/null 2>&1
      if [ $? -eq 0 ] ; then
          echo "Already Running."
          log_end_msg 1
          exit 1
      fi	
      echo "Removing Stale PID file"
      rm -f ${PID_FILE}
    fi

    log_progress_msg "untangle-pyconnector"    
    start-stop-daemon -m --pidfile ${PID_FILE} --name ${DAEMON_NAME} --background --start --startas ${BIN_NAME} -- ${OPTIONS}

    log_end_msg 0	
}

stop()
{
    log_daemon_msg "Stopping $DESC"

    log_progress_msg "untangle-pyconnector"    
    start-stop-daemon --pidfile ${PID_FILE} --stop --retry USR1/4/USR1/2/USR1/2/INT/1/TERM/1/KILL/1
    RET=$?
    log_end_msg $RET

    rm -f ${PID_FILE}
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|restart|force-reload)
        stop
        start
        ;;
    *)
        /bin/echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
