#!/bin/bash

### BEGIN INIT INFO
# Provides:          untangle-reports
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Author: Sebastien Delafond <seb@untangle.com>

source /lib/lsb/init-functions

if [ -f @PREFIX@/etc/default/untangle-vm ] ; then
    source @PREFIX@/etc/default/untangle-vm
fi

DESC="${OEM_NAME} Reports"
NAME="reports"
DAEMON="@PREFIX@/usr/share/untangle/bin/reporting-wrapper.sh"
PID_FILE="@PREFIX@/var/run/untangle-reports-wrapper.pid"

start() {
  log_daemon_msg "Starting $DESC"

  if [ -f ${PID_FILE} ] ; then
    ps -p `cat ${PID_FILE}` > /dev/null 2>&1
    if [ $? -eq 0 ] ; then
      echo "Already Running."
      log_end_msg 1
      exit 1
    else
      echo "Removing stale pidfile"
      rm -f ${PID_FILE}
    fi
  fi

  log_progress_msg "untangle-reports"    
  start-stop-daemon -m --pidfile ${PID_FILE} --name ${NAME} --start --background --exec ${DAEMON} 2>&1
  RET=$?
  log_end_msg $RET
  [ $RET = 0 ] || exit $RET
}

stop() {
  log_daemon_msg "Stopping $DESC"

  log_progress_msg "untangle-reports"    
  start-stop-daemon --pidfile ${PID_FILE} --stop --retry USR1/4/USR1/4/USR1/2/INT/1/TERM/1/KILL/1 > /dev/null 2>&1
  RET=$?
  pkill -f /usr/lib/python2.5/reports/server.py
  log_end_msg $RET
  rm -f ${PID_FILE}
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|restart|force-reload)
        stop
        start
        ;;
    *)
        /bin/echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
