#! /bin/bash

exec > /dev/null 2>&1

REGDONE="@UVM_HOME@/.regdone"
REGINFO="@UVM_HOME@/registration.info"

if [ -f "@UVM_HOME@/activation.key" ]; then
    mkdir -p @UVM_HOME@/autodump @UVM_HOME@/tmp

    @UVM_HOME@/bin/uvmdb-backup @UVM_HOME@/autodump
    /usr/bin/find @UVM_HOME@/autodump -type f -mtime +31 | /usr/bin/xargs -r /bin/rm

    /usr/bin/find /tmp -mtime +31 -name "*.tmp" | /usr/bin/xargs -r /bin/rm
    /usr/bin/find @UVM_HOME@/tmp -name velocity -prune -o -type f -mtime +15 -print | /usr/bin/xargs -r /bin/rm

    @UVM_HOME@/bin/generate-reports.py

    yesterday=$(date --date="1 day ago" "+%y-%m-%d")
    for trial in $(/usr/share/untangle/bin/expiring_packages $yesterday) ; do
      @UVM_HOME@/bin/generate-reports.py -t $trial
    done

    @UVM_HOME@/bin/utregister

    ## Ignore errors here.
    if [ -x "@UVM_HOME@/bin/update_blockpage" ]; then
        @UVM_HOME@/bin/update_blockpage || true
    fi
fi

exit 0
