/*
 * Copyright (c) 2003-2007 Untangle, Inc.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Untangle, Inc. ("Confidential Information"). You shall
 * not disclose such Confidential Information.
 *
 * $Id$
 */


#ifndef __JNI_HEADER_H_
#define __JNI_HEADER_H_

/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! *
 * This file is autogenerated, do not edit manually, edit java_header_src.sh instead *
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */

// JN Build standard name eg com_untangle_${c_package}_Class_name
// JF Build function name eg Java_com_untangle_${c_package}_Class_name
// JP Build path
#define JN_BUILD_NAME(CLASS,NAME)  com_untangle_jvector_ ## CLASS ## _ ## NAME
#define JF_BUILD_NAME(CLASS,FUNC)  Java_ ## com_untangle_jvector_ ## CLASS ## _ ## FUNC
#define JP_BUILD_NAME(OBJ)         "com/untangle/jvector/" #OBJ

#define JH_Vector       "com_untangle_jvector_Vector.h"
#define JN_Vector(VAL)  JN_BUILD_NAME( Vector, VAL )
#define JF_Vector(FUNC) JF_BUILD_NAME( Vector, FUNC )
#define JP_Vector       JP_BUILD_NAME( Vector )

#define JH_IncomingSocketQueue       "com_untangle_jvector_IncomingSocketQueue.h"
#define JN_IncomingSocketQueue(VAL)  JN_BUILD_NAME( IncomingSocketQueue, VAL )
#define JF_IncomingSocketQueue(FUNC) JF_BUILD_NAME( IncomingSocketQueue, FUNC )
#define JP_IncomingSocketQueue       JP_BUILD_NAME( IncomingSocketQueue )

#define JH_OutgoingSocketQueue       "com_untangle_jvector_OutgoingSocketQueue.h"
#define JN_OutgoingSocketQueue(VAL)  JN_BUILD_NAME( OutgoingSocketQueue, VAL )
#define JF_OutgoingSocketQueue(FUNC) JF_BUILD_NAME( OutgoingSocketQueue, FUNC )
#define JP_OutgoingSocketQueue       JP_BUILD_NAME( OutgoingSocketQueue )

#define JH_TCPSink       "com_untangle_jvector_TCPSink.h"
#define JN_TCPSink(VAL)  JN_BUILD_NAME( TCPSink, VAL )
#define JF_TCPSink(FUNC) JF_BUILD_NAME( TCPSink, FUNC )
#define JP_TCPSink       JP_BUILD_NAME( TCPSink )

#define JH_TCPSource       "com_untangle_jvector_TCPSource.h"
#define JN_TCPSource(VAL)  JN_BUILD_NAME( TCPSource, VAL )
#define JF_TCPSource(FUNC) JF_BUILD_NAME( TCPSource, FUNC )
#define JP_TCPSource       JP_BUILD_NAME( TCPSource )

#define JH_Relay       "com_untangle_jvector_Relay.h"
#define JN_Relay(VAL)  JN_BUILD_NAME( Relay, VAL )
#define JF_Relay(FUNC) JF_BUILD_NAME( Relay, FUNC )
#define JP_Relay       JP_BUILD_NAME( Relay )

#define JH_Crumb       "com_untangle_jvector_Crumb.h"
#define JN_Crumb(VAL)  JN_BUILD_NAME( Crumb, VAL )
#define JF_Crumb(FUNC) JF_BUILD_NAME( Crumb, FUNC )
#define JP_Crumb       JP_BUILD_NAME( Crumb )

#define JH_Source       "com_untangle_jvector_Source.h"
#define JN_Source(VAL)  JN_BUILD_NAME( Source, VAL )
#define JF_Source(FUNC) JF_BUILD_NAME( Source, FUNC )
#define JP_Source       JP_BUILD_NAME( Source )

#define JH_Sink       "com_untangle_jvector_Sink.h"
#define JN_Sink(VAL)  JN_BUILD_NAME( Sink, VAL )
#define JF_Sink(FUNC) JF_BUILD_NAME( Sink, FUNC )
#define JP_Sink       JP_BUILD_NAME( Sink )

#define JH_UDPSource       "com_untangle_jvector_UDPSource.h"
#define JN_UDPSource(VAL)  JN_BUILD_NAME( UDPSource, VAL )
#define JF_UDPSource(FUNC) JF_BUILD_NAME( UDPSource, FUNC )
#define JP_UDPSource       JP_BUILD_NAME( UDPSource )

#define JH_UDPSink       "com_untangle_jvector_UDPSink.h"
#define JN_UDPSink(VAL)  JN_BUILD_NAME( UDPSink, VAL )
#define JF_UDPSink(FUNC) JF_BUILD_NAME( UDPSink, FUNC )
#define JP_UDPSink       JP_BUILD_NAME( UDPSink )
 
#endif  // __JNI_HEADER_H_

