#!/bin/dash

BACKUP_DIR=/var/backup/untangle-net-alpaca
BACKUP_SCRIPT=/usr/share/untangle-net-alpaca/scripts/backup

BASE_DIR=/var/lib/rails/untangle-net-alpaca/

## rails environment, defaults to production
MONGREL_ENV="production"

trap "restartAlpaca" EXIT

restartAlpaca()
{
    /etc/init.d/untangle-net-alpaca restart
}

backupSettings()
{
    local t_name=$1
    mkdir -p ${BACKUP_DIR}
    if [ -x "${BACKUP_SCRIPT}" ]; then
        ${BACKUP_SCRIPT} ${BACKUP_DIR}/${t_name}-`date +"%y%m%d%H%M"`.uab "Upgrade Backup"
    else
        echo "${BACKUP_SCRIPT} doesn't exist"
    fi
}

backupSettings "pre-upgrade"

## Stop the alpaca
/etc/init.d/untangle-net-alpaca stop

## Delete all of the databases
rm -f ${BASE_DIR}/database/*.db

## Change into the directory and convert the settings
cd ${BASE_DIR} && {
    rake alpaca:upgrade RAILS_ENV=${MONGREL_ENV} || echo "Unable to migrate the network settings from the UVM to the alapca."  
} || {
    echo "Unable to change into the alpaca directory (${BASE_DIR})"
}

## Backup the settings again
backupSettings "post-upgrade"
