#!/bin/sh

exec >> @UVM_LOG@/iptables.log 2>&1

ACTION=${1:-restart}

if [ "${ACTION}x" == "stop" ]; then
    echo "[DEBUG:`date`] Stopping DNS masq"
    /etc/init.d/dnsmasq stop
    exit 0
fi

FORCE_RESTART=${2:-true}
DNSMASQ_HASH="@UVM_CONF@/dnsmasq-hash"

NEW_HASH=`mktemp`

md5sum /etc/dnsmasq.conf /etc/hosts /etc/resolv.conf > ${NEW_HASH}

currentPid=`pidof dnsmasq`
expectedPid=`cat /var/run/dnsmasq.pid`

## Always do a restart
if [ -z "${currentPid}" ] || [ "${currentPid}x" != "${expectedPid}x" ]; then
    echo "[DEBUG:`date`] Forcing a restart of dnsmasq"
    FORCE_RESTART=true
fi

if [ ${FORCE_RESTART} == "false" ] && [ -f ${DNSMASQ_HASH} ]; then
    ## If they are the same do nothing
    diff ${NEW_HASH} ${DNSMASQ_HASH} > /dev/null 2>&1 && { 
        echo "[DEBUG:`date`] Skipping dnsmasq restart" 
        rm -f ${NEW_HASH}
        exit 0 
    }

    ## If the host files differ, just send a SIGHUP
    diff -I '\/etc\/hosts' ${NEW_HASH} ${DNSMASQ_HASH} > /dev/null 2>&1 && {
        echo "[DEBUG:`date`] sending dnsmasq SIGHUP to reload host file." 
        kill -HUP ${currentPid}
        mv ${NEW_HASH} ${DNSMASQ_HASH}
        exit 0
    }
fi

## Otherwise force a restart
echo "[DEBUG:`date`] Restarting dnsmasq." 
/etc/init.d/dnsmasq restart

mv ${NEW_HASH} ${DNSMASQ_HASH}

