#!/bin/sh

exec >> @UVM_LOG@/iptables.log 2>&1

FUNCTIONS_FILE=@UVM_HOME@/networking/functions

if [ -r ${FUNCTIONS_FILE} ]; then
    . ${FUNCTIONS_FILE}
else
    echo "Unable to load the functions file ${FUNCTIONS_FILE}"
    exit -1
fi

echo "Flushing all of the rules and deleting all of the chains"

## Flush all of the rules
flush