#!/bin/sh

REGDONE="@UVM_HOME@/.regdone"
REGINFO="@UVM_HOME@/registration.info"

if [ -f "@UVM_HOME@/activation.key" ]; then
    mkdir -p @UVM_HOME@/autodump
    /usr/bin/uvmdb-backup local @UVM_HOME@/autodump

    /usr/bin/update-reports &> @UVM_LOG@/report.log

    /usr/bin/find /tmp -mtime +31 -name "*.tmp" | /usr/bin/xargs -r /bin/rm
    /usr/bin/find @UVM_HOME@/tmp -name velocity -prune -type f -mtime +31 | /usr/bin/xargs -r /bin/rm
    /usr/bin/find @UVM_HOME@/autodump -type f -mtime +31 | /usr/bin/xargs -r /bin/rm

    if [ -f "$REGINFO" ]; then
        if [ ! -f "$REGDONE" -o "$REGDONE" -ot "$REGINFO" ]; then
            /usr/bin/mvregister
        fi
    fi
fi
