#! /bin/bash

REGDONE="@UVM_HOME@/.regdone"
REGINFO="@UVM_HOME@/registration.info"

if [ -f "@UVM_HOME@/activation.key" ]; then
    mkdir -p @UVM_HOME@/autodump @UVM_HOME@/tmp

    /usr/bin/uvmdb-backup local @UVM_HOME@/autodump > /dev/null 2>&1
    /usr/bin/find @UVM_HOME@/autodump -type f -mtime +31 | /usr/bin/xargs -r /bin/rm

    /usr/bin/find /tmp -mtime +31 -name "*.tmp" | /usr/bin/xargs -r /bin/rm
    /usr/bin/find @UVM_HOME@/tmp -name velocity -prune -o -type f -mtime +15 -print | /usr/bin/xargs -r /bin/rm

    /usr/lib/python2.5/reports/process.py >> @UVM_LOG@/report.log 2>&1

    @UVM_HOME@/bin/utregister

    if [ -x "@UVM_HOME@/bin/update_blockpage" ]; then
        @UVM_HOME@/bin/update_blockpage
    fi
fi


exit 0
