#!/bin/dash

# If openvpn is running - restart it
if [ ! -z "`pidof openvpn`" ] ; then
    systemctl --no-block restart openvpn
fi

# Call the openvpn app script to generate the interface status
# files using the values from the application settings
echo "Creating interface status files"
/usr/share/untangle/bin/openvpn-create-statfile

# Check the interface ID file
if [ ! -f /var/lib/interface-status/interface-250-status.js ] ; then
    echo "Missing status file: /var/lib/interface-status/interface-250-status.js"
fi

# Check the interface name file
if [ ! -f /var/lib/interface-status/interface-tun0-status.js ] ; then
    echo "Missing status file: /var/lib/interface-status/interface-tun0-status.js"
fi
