/*
 * Copyright (c) 2003, 2004, 2005 Metavize Inc.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Metavize Inc. ("Confidential Information").  You shall
 * not disclose such Confidential Information.
 *
 */
package com.metavize.tran.protofilter;

import java.util.LinkedHashMap;

/**
 * <b>WARNING WARNING WARNING WARNING WARNING WARNING</b>
 *
 * This class is autogenerated, do not edit
 *
 * <b>WARNING WARNING WARNING WARNING WARNING WARNING</b>
 */
public class LoadPatterns {

    private LoadPatterns() {}

    public static LinkedHashMap getPatterns()
    {
        // Now that we have Policies,  we create a new map every time since we don't want sharing.
        return createPatterns();
    }

    private static LinkedHashMap createPatterns()
    {
        LinkedHashMap pats = new LinkedHashMap();

